module Test.FrontendContractsSpec
    ( tests
    ) where

import qualified Data.Text as Text
import qualified Data.Text.IO as Text
import IHP.Prelude
import System.Directory (listDirectory)
import System.FilePath ((</>))
import Test.Hspec

import Application.Helper.Frontend.Contracts (frontendContractDeclarations,
                                              frontendContractsTypeScript)
import Application.Helper.Frontend.TypeScript (TypeScriptDeclaration (..),
                                               TypeScriptDeclarationOrigin (..))

tests :: Spec
tests = describe "Frontend contract generator foundation" do
    it "keeps the public generated file entrypoint intact" do
        frontendContractsTypeScript `shouldSatisfy` Text.isPrefixOf "// @generated by Application.Helper.Frontend.Contracts"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export type OverlayLane"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export type AesonTypeScriptSpikeSimpleEnum"

    it "marks aeson-typescript prototype declarations as Haskell-schema generated" do
        let declarationOrigins = [(declaration.name, declaration.origin) | declaration <- frontendContractDeclarations]
        declarationOrigins `shouldContain` [("AesonTypeScriptSpike", HaskellSchemaGenerated)]
        declarationOrigins `shouldContain` [("LiveUpdateContracts", HaskellSchemaGenerated)]
        declarationOrigins `shouldContain` [("InteractionContracts", HaskellSchemaGenerated)]

    it "keeps the composition root free of large handwritten protocol blocks" do
        source <- Text.readFile "Application/Helper/Frontend/Contracts.hs"
        source `shouldNotSatisfy` Text.isInfixOf "export type LiveUpdateScope"
        source `shouldNotSatisfy` Text.isInfixOf "export const InteractionDom"
        source `shouldNotSatisfy` Text.isInfixOf "Text.unlines"

    it "isolates temporary legacy manual declarations to the compatibility module" do
        files <- listDirectory "Application/Helper/Frontend"
        offenders <- fmap catMaybes $ forM files \fileName -> do
            let path = "Application/Helper/Frontend" </> fileName
            source <- Text.readFile path
            pure $
                if Text.isInfixOf "legacyManualDeclaration" source
                    && fileName /= "LegacyManualContracts.hs"
                    && fileName /= "TypeScript.hs"
                    then Just path
                    else Nothing
        offenders `shouldBe` []

    it "does not leave migrated protocols in the legacy manual block" do
        source <- Text.readFile "Application/Helper/Frontend/LegacyManualContracts.hs"
        source `shouldNotSatisfy` Text.isInfixOf "export type LiveUpdateScope"
        source `shouldNotSatisfy` Text.isInfixOf "export type LiveUpdateMessage"
        source `shouldNotSatisfy` Text.isInfixOf "export type LiveUpdateCommand"
        source `shouldNotSatisfy` Text.isInfixOf "export const InteractionDom"
        source `shouldNotSatisfy` Text.isInfixOf "IntentFormContract"
