{-# LANGUAGE LambdaCase          #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE TypeApplications    #-}

module Test.FrontendContractsSpec
    ( tests
    ) where

import qualified Application.Helper.FrontendContract.App as App
import qualified Application.Helper.FrontendContract.AppShell as AppShell
import Application.Helper.FrontendContract.AppShell.Runtime (AppShellActionRoute (..),
                                                             appShellActionByMarker,
                                                             appShellActionHtmxAttrPairs)
import Application.Helper.FrontendContract.AppValues (AppEvents (..),
                                                      AppOverlayDom (..),
                                                      canonicalAppEvents,
                                                      canonicalAppOverlayDom,
                                                      interactionIntentSubmitHtmxTrigger,
                                                      sharedDialogOverlayMountId,
                                                      sharedToastOverlayMountId)
import Application.Helper.FrontendContract.Contracts (TypeScriptDeclaration (..),
                                                      TypeScriptDeclarationOrigin (..),
                                                      frontendContractDeclarations,
                                                      frontendContractsTypeScript)
import qualified Application.Helper.FrontendContract.Htmx as Htmx
import qualified Application.Helper.FrontendContract.IR as Contract
import qualified Application.Helper.FrontendContract.LiveUpdate as LiveContract
import Application.Helper.FrontendContract.LiveUpdateValues (liveUpdateClientIdHeaderName,
                                                             liveUpdateSocketPathSegment,
                                                             surfaceActionDomAttribute,
                                                             surfaceConfigDomAttribute,
                                                             surfaceDomAttribute)
import qualified Application.Helper.FrontendContract.Naming as Naming
import Application.Helper.FrontendContract.Registry (registeredFrontendContractIR)
import Application.Helper.FrontendContract.RosterValues (RosterStaffSortKey (..),
                                                         rosterStaffSortKeyAttribute,
                                                         rosterStaffSortKeyValues)
import qualified Application.Helper.FrontendContract.Surface.ContractIR as SurfaceIR
import Application.Helper.FrontendContract.Surface.Contracts (registeredFrontendSurfaceContractIR)
import Application.Helper.FrontendContract.Surface.Reflect (reflectSurfaceSpec)
import Application.Helper.FrontendContract.Values (domIdValue, enumLiteralValue,
                                                   eventNameValue,
                                                   lookupDomIdValue,
                                                   lookupEnumLiteralValue,
                                                   lookupEventNameValue)
import Application.Helper.FrontendContract.Wire.Json (validateContractMarkerValue,
                                                      validateContractMarkerValueWith,
                                                      validateSurfaceFragmentKeyValue,
                                                      validateSurfaceScopeValue,
                                                      validateWireValue)
import qualified Application.Helper.FrontendContract.Wire.LiveUpdate as Live
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as KeyMap
import qualified Data.Aeson.Types as AesonTypes
import qualified Data.ByteString.Lazy as LBS
import Data.Either (isLeft, isRight)
import qualified Data.List as List
import qualified Data.Text as Text
import qualified Data.Text.Encoding as TextEncoding
import qualified Data.Text.IO as Text
import IHP.Prelude
import Test.Hspec
import qualified Test.Support.FrontendSurfaceFixture as SurfaceFixture

data SpecNested
data SpecRecord
data SpecUnion

tests :: Spec
tests = describe "Frontend contract generator foundation" do
    it "keeps the public generated file entrypoint FrontendContract-owned" do
        frontendContractsTypeScript `shouldSatisfy` Text.isPrefixOf "// @generated by Application.Helper.FrontendContract.Contracts"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export type RosterStaffSortKey"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export type SurfaceScope"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export type LiveUpdateCommand"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export type UiRegionTransitionProfile"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export type InteractionSessionEffect"

    it "shares reflected live endpoint, header, and mount DOM constants across Haskell and TypeScript" do
        liveUpdateSocketPathSegment `shouldBe` "live-updates"
        liveUpdateClientIdHeaderName `shouldBe` "X-Live-Update-Client-Id"
        surfaceDomAttribute `shouldBe` "data-bepis-surface"
        surfaceConfigDomAttribute `shouldBe` "data-bepis-surface-config"
        surfaceActionDomAttribute `shouldBe` "data-bepis-surface-action"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export const liveUpdateSocketPath = \"live-updates\" as const;"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export const liveUpdateClientIdHeader = \"X-Live-Update-Client-Id\" as const;"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export const surfaceDomAttr = \"data-bepis-surface\" as const;"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export const surfaceConfigDomAttr = \"data-bepis-surface-config\" as const;"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export const surfaceActionDomAttr = \"data-bepis-surface-action\" as const;"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "sourceRef: sourceRefDomAttr"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export const rosterContentDomToken = \"roster-content\" as const;"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export const rosterWeekShellDomToken = \"roster-week-shell\" as const;"

    it "registers one generated FrontendContract declaration block" do
        [(declaration.name, declaration.origin) | declaration <- frontendContractDeclarations]
            `shouldBe` [("FrontendContractGlobals", HaskellSchemaGenerated)]

    it "keeps checked-in contracts byte-identical to the reflection-backed generator" do
        checkedIn <- Text.readFile "frontend/ts/generated/contracts.ts"
        checkedIn `shouldBe` frontendContractsTypeScript

    it "keeps executable fragment descriptors out of the live wire contract" do
        let generatedTypes = generatedContractTypeNames frontendContractsTypeScript
        forM_ ["SurfaceFragmentKey", "SurfaceSubscription", "LiveFragmentsRefreshEventDetail"] \name ->
            generatedTypes `shouldContain` [name]
        forM_ ["SurfaceWireFragment", "SurfaceFragmentProtection"] \name ->
            generatedTypes `shouldNotContain` [name]
        frontendContractsTypeScript
            `shouldSatisfy` Text.isInfixOf "export type SurfaceSubscription = { scope: SurfaceScope; scopeKey: string; fragments: ReadonlyArray<SurfaceFragmentKey> };"

    it "embeds the checked Surface topology directly in the unified registry" do
        registeredFrontendContractIR.contractSurfaces
            `shouldBe` registeredFrontendSurfaceContractIR.contractSurfaces

    it "uses the canonical field, wire, schema, and HTMX core inside an unregistered Surface fixture" do
        let fixture = reflectSurfaceSpec @SurfaceFixture.FrontendSurfaceFixture
        let scopeFields :: [Contract.FieldIR] = concatMap (.scopeFields) fixture.surfaceScopes
        let dtoSchemas :: [Contract.SchemaIR] = fixture.surfaceDtos
        let actionOptions :: [Contract.HtmxActionOptionIR] = concatMap (Contract.optionHtmxActionOptions . (.htmxActionOptions)) fixture.surfaceHtmxActions

        map (\field -> (field.fieldName, field.fieldWire)) scopeFields
            `shouldBe` [("venueId", Contract.WireUuidIR), ("weekOffset", Contract.WireIntIR)]
        map Contract.schemaNameAndMarker dtoSchemas
            `shouldBe` [("FixturePayload", "FixturePayload"), ("FixtureRelatedPayload", "FixtureRelatedPayload")]
        actionOptions `shouldContain` [Contract.HtmxActionMethodIR Contract.HtmxPostIR]

    it "declares exceptional browser projections in closed IR instead of root-name switches" do
        let projections =
                [ projection
                | global <- registeredFrontendContractIR.contractGlobals
                , Contract.GlobalProjectionIR projection <- global.globalPrimitives
                ]
        projections `shouldBe` [Contract.InteractionDomProjectionIR]

    it "uses one shared HTMX metadata model for generated request primitives" do
        let genericOptions =
                [ Contract.HtmxActionMethodIR Contract.HtmxPostIR
                , Contract.HtmxActionTriggerIR (Contract.HtmxTypedSyntaxIR "change" [])
                , Contract.HtmxActionIncludeIR (Contract.HtmxTypedSyntaxIR "#filters" [])
                , Contract.HtmxActionSyncIR (Contract.HtmxTypedSyntaxIR "closest form:queue" [])
                , Contract.HtmxActionIndicatorIR (Contract.HtmxTypedSyntaxIR "#spinner" [])
                , Contract.HtmxActionConfirmIR "Continue?"
                , Contract.HtmxActionSelectIR (Contract.HtmxTypedSyntaxIR "#fragment" [])
                , Contract.HtmxActionTargetIR (Contract.HtmxTypedSyntaxIR "#target" [])
                , Contract.HtmxActionSwapIR (Contract.HtmxTypedSyntaxIR "outerHTML" [])
                , Contract.HtmxActionPushUrlIR Contract.HtmxPushUrlFalseIR
                , Contract.HtmxActionCustomHtmxIR "custom-marker" "fixture escape hatch"
                ]
        let surfaceOptions =
                map SurfaceIR.HtmxOption genericOptions
        Contract.optionHtmxActionOptions surfaceOptions `shouldBe` genericOptions
        let metadata = Htmx.htmxActionMetadataFromOptions genericOptions
        metadata `shouldBe` Htmx.htmxActionMetadataFromSurfaceOptions surfaceOptions
        Htmx.htmxActionOptionAttrPairs metadata
            `shouldBe` [ ("hx-trigger", "change")
                       , ("hx-include", "#filters")
                       , ("hx-sync", "closest form:queue")
                       , ("hx-indicator", "#spinner")
                       , ("hx-confirm", "Continue?")
                       , ("hx-select", "#fragment")
                       , ("hx-target", "#target")
                       , ("hx-swap", "outerHTML")
                       , ("hx-push-url", "false")
                       ]

    it "reflects generated AppShell action manifests and runtime attrs" do
        let appShellActions =
                [ action
                | global <- registeredFrontendContractIR.contractGlobals
                , Contract.GlobalAppShellActionIR action <- global.globalPrimitives
                ]
        let partialNavigateAction = appShellActionByMarker @AppShell.PartialNavigate
        let openFeedbackDialogAction = appShellActionByMarker @AppShell.OpenFeedbackDialog
        fmap (.appShellActionName) (find ((== "partial-navigate") . (.appShellActionName)) appShellActions) `shouldBe` Just "partial-navigate"
        partialNavigateAction.appShellActionOptions
            `shouldBe` [ Contract.HtmxActionMethodIR Contract.HtmxGetIR
                       , Contract.HtmxActionCustomHtmxIR "partial-navigation-htmx-attrs" "partial navigation supplies route-specific target, swap, select, push-url, and sync attrs"
                       ]
        openFeedbackDialogAction.appShellActionOptions
            `shouldBe` [ Contract.HtmxActionMethodIR Contract.HtmxGetIR
                       , Contract.HtmxActionTargetIR (Contract.HtmxTypedSyntaxIR "#dialog-overlay-mount" ["dialog-overlay-mount"])
                       , Contract.HtmxActionSwapIR (Contract.HtmxTypedSyntaxIR "innerHTML" [])
                       , Contract.HtmxActionPushUrlIR Contract.HtmxPushUrlFalseIR
                       ]
        let partialNavigateAttrs = appShellActionHtmxAttrPairs partialNavigateAction AppShellActionRoute
                { appShellActionRouteUrl = "/next"
                , appShellActionRouteFields = []
                , appShellActionRouteCustomHtmx = []
                , appShellActionRouteStandardUrl = Nothing
                , appShellActionRouteExtraAttrs = []
                }
        partialNavigateAttrs `shouldContain` [("hx-get", "/next")]
        partialNavigateAttrs `shouldNotContain` [("data-bepis-app-shell-action", "partial-navigate")]
        frontendContractsTypeScript `shouldNotSatisfy` Text.isInfixOf "AppShellActionManifest"
        frontendContractsTypeScript `shouldNotSatisfy` Text.isInfixOf "partialNavigateAppShellActionManifest"
        frontendContractsTypeScript `shouldNotSatisfy` Text.isInfixOf "openFeedbackDialogAppShellActionManifest"

    it "reflects generated app shell action manifests" do
        let appShellActions =
                [ action
                | global <- registeredFrontendContractIR.contractGlobals
                , Contract.GlobalAppShellActionIR action <- global.globalPrimitives
                ]
        let openFeedbackAction = find ((== "open-feedback-dialog") . (.appShellActionName)) appShellActions
        fmap (.appShellActionFields) openFeedbackAction `shouldBe` Just []
        fmap (.appShellActionOptions) openFeedbackAction
            `shouldBe` Just
                [ Contract.HtmxActionMethodIR Contract.HtmxGetIR
                , Contract.HtmxActionTargetIR (Contract.HtmxTypedSyntaxIR "#dialog-overlay-mount" ["dialog-overlay-mount"])
                , Contract.HtmxActionSwapIR (Contract.HtmxTypedSyntaxIR "innerHTML" [])
                , Contract.HtmxActionPushUrlIR Contract.HtmxPushUrlFalseIR
                ]
        let submitFeedbackAction = find ((== "submit-feedback") . (.appShellActionName)) appShellActions
        fmap (fmap (.fieldName) . (.appShellActionFields)) submitFeedbackAction `shouldBe` Just ["feedbackType", "content"]
        fmap (.appShellActionOptions) submitFeedbackAction
            `shouldBe` Just
                [ Contract.HtmxActionMethodIR Contract.HtmxPostIR
                , Contract.HtmxActionTargetIR (Contract.HtmxTypedSyntaxIR "#dialog-overlay-mount" ["dialog-overlay-mount"])
                , Contract.HtmxActionSwapIR (Contract.HtmxTypedSyntaxIR "innerHTML" [])
                , Contract.HtmxActionPushUrlIR Contract.HtmxPushUrlFalseIR
                ]

    it "exposes consistent Profile and Staff surface profile action field sets" do
        let surfaceActions surfaceName actionName =
                [ action.htmxActionName
                | surface <- registeredFrontendContractIR.contractSurfaces
                , surface.surfaceName == surfaceName
                , action <- surface.surfaceHtmxActions
                , action.htmxActionName == actionName
                ]
        let actionFields surfaceName actionName =
                [ action.htmxActionFields
                | surface <- registeredFrontendContractIR.contractSurfaces
                , surface.surfaceName == surfaceName
                , action <- surface.surfaceHtmxActions
                , action.htmxActionName == actionName
                ]
        surfaceActions "staff" "update-staff-profile" `shouldBe` ["update-staff-profile"]
        actionFields "profile" "update-profile-details" `shouldBe` actionFields "staff" "update-staff-profile"
        actionFields "profile" "update-profile-shift-preferences" `shouldBe` actionFields "staff" "update-staff-shift-preferences"
        frontendContractsTypeScript `shouldNotSatisfy` Text.isInfixOf "staffSurfaceManifest"

    it "resolves canonical Haskell value accessors from registered FrontendContract IR" do
        lookupDomIdValue @App.DialogOverlayMount `shouldBe` Right sharedDialogOverlayMountId
        lookupDomIdValue @App.ToastOverlayMount `shouldBe` Right sharedToastOverlayMountId
        lookupEventNameValue @App.IntentSubmit `shouldBe` Right interactionIntentSubmitHtmxTrigger
        lookupEnumLiteralValue @App.RosterStaffSortKey @App.Name `shouldBe` Right "name"
        domIdValue @App.DialogOverlayMount `shouldBe` canonicalAppOverlayDom.appDialogOverlayMountId
        eventNameValue @App.IntentSubmit `shouldBe` canonicalAppEvents.appInteractionIntentSubmitEventName
        enumLiteralValue @App.RosterStaffSortKey @App.Name `shouldBe` rosterStaffSortKeyAttribute RosterStaffSortByName
        rosterStaffSortKeyValues
            `shouldBe` [ (RosterStaffSortByName, "name")
                       , (RosterStaffSortByRole, "role")
                       , (RosterStaffSortByShifts, "shifts")
                       ]

    it "returns deterministic diagnostics for missing Haskell value accessors" do
        lookupDomIdValue @Text `shouldBe` Left "No FrontendContract DomId declaration for marker Text"
        lookupEventNameValue @Text `shouldBe` Left "No FrontendContract Event declaration for marker Text"
        lookupEnumLiteralValue @Text @Text `shouldBe` Left "No FrontendContract enum case Text for enum marker Text"

    it "validates records, refs, arrays, nullable fields, and tagged unions through the IR JSON interpreter" do
        let scope = Live.SurfaceScope "timesheets" (Aeson.object ["venueId" Aeson..= ("11111111-1111-1111-1111-111111111111" :: Text), "weekOffset" Aeson..= (4 :: Int)])
        let fragmentKey = Live.SurfaceFragmentKey "timesheets" "timesheet-day-section" (Aeson.object ["dayOffset" Aeson..= (2 :: Int)])
        let subscription = Live.SurfaceSubscription scope "timesheets:11111111-1111-1111-1111-111111111111:4" [fragmentKey]
        let command = Live.Subscribe subscription "client-1" (Just 9)
        let message = Live.Invalidate scope "timesheets:11111111-1111-1111-1111-111111111111:4" 10 [fragmentKey] (Just "client-2")

        AesonTypes.parseEither (validateContractMarkerValue @LiveContract.SurfaceSubscription) (Aeson.toJSON subscription) `shouldSatisfy` isRight
        AesonTypes.parseEither (validateContractMarkerValue @LiveContract.LiveUpdateCommand) (Aeson.toJSON command) `shouldSatisfy` isRight
        AesonTypes.parseEither (validateContractMarkerValue @LiveContract.LiveUpdateMessage) (Aeson.toJSON message) `shouldSatisfy` isRight
        Aeson.eitherDecode (Aeson.encode command) `shouldBe` Right command
        Aeson.eitherDecode (Aeson.encode message) `shouldBe` Right message

    it "rejects invalid surface scopes, fragments, enum values, and union discriminators through the IR JSON interpreter" do
        let badScope = Aeson.object ["surface" Aeson..= ("missing" :: Text), "scope" Aeson..= Aeson.object []]
        let badFragment = Aeson.object ["surface" Aeson..= ("timesheets" :: Text), "kind" Aeson..= ("missing" :: Text), "params" Aeson..= Aeson.object []]
        let badCommand = Aeson.object ["type" Aeson..= ("missing" :: Text)]

        AesonTypes.parseEither validateSurfaceScopeValue badScope `shouldSatisfy` isLeft
        AesonTypes.parseEither validateSurfaceFragmentKeyValue badFragment `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractMarkerValue @LiveContract.LiveUpdateCommand) badCommand `shouldSatisfy` isLeft

    it "covers Wire.Json field presence, nested refs, arrays, enums, and tagged unions" do
        let contract = wireJsonSpecContract
        let goodNested = Aeson.object
                [ "name" Aeson..= ("Ada" :: Text)
                , "count" Aeson..= (3 :: Int)
                , "active" Aeson..= True
                , "uuid" Aeson..= ("not-a-uuid-but-contract-string" :: Text)
                , "day" Aeson..= ("not-a-day-but-contract-string" :: Text)
                , "tags" Aeson..= (["alpha", "beta"] :: [Text])
                , "maybeText" Aeson..= Aeson.Null
                , "nullableText" Aeson..= Aeson.Null
                , "status" Aeson..= ("ready" :: Text)
                , "literal" Aeson..= ("special-case" :: Text)
                ]
        let goodRecord = Aeson.object
                [ "nested" Aeson..= goodNested
                , "items" Aeson..= [goodNested]
                ]
        AesonTypes.parseEither (validateContractMarkerValueWith @SpecRecord contract) goodRecord `shouldSatisfy` isRight
        AesonTypes.parseEither (validateContractMarkerValueWith @SpecUnion contract) (Aeson.object ["kind" Aeson..= ("one" :: Text), "value" Aeson..= goodNested]) `shouldSatisfy` isRight
        AesonTypes.parseEither (validateContractMarkerValueWith @SpecUnion contract) (Aeson.object ["kind" Aeson..= ("two" :: Text), "note" Aeson..= ("ok" :: Text)]) `shouldSatisfy` isRight
        AesonTypes.parseEither (validateWireValue "uuid" Contract.WireUuidIR) (Aeson.String "not-a-uuid-but-contract-string") `shouldSatisfy` isRight
        AesonTypes.parseEither (validateWireValue "day" Contract.WireDayIR) (Aeson.String "not-a-day-but-contract-string") `shouldSatisfy` isRight

        AesonTypes.parseEither (validateContractMarkerValueWith @SpecNested contract) (addJsonField "extra" (Aeson.Bool True) goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractMarkerValueWith @SpecNested contract) (removeJsonField "name" goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractMarkerValueWith @SpecNested contract) (removeJsonField "maybeText" goodNested) `shouldSatisfy` isRight
        AesonTypes.parseEither (validateContractMarkerValueWith @SpecNested contract) (removeJsonField "nullableText" goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractMarkerValueWith @SpecNested contract) (replaceJsonField "name" (Aeson.Number 1) goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractMarkerValueWith @SpecNested contract) (replaceJsonField "count" (Aeson.Number 1.5) goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractMarkerValueWith @SpecNested contract) (replaceJsonField "tags" (Aeson.String "alpha") goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractMarkerValueWith @SpecNested contract) (replaceJsonField "status" (Aeson.String "missing") goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractMarkerValueWith @SpecNested contract) (replaceJsonField "literal" (Aeson.String "case") goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractMarkerValueWith @SpecRecord contract) (replaceJsonField "nested" (Aeson.object []) goodRecord) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractMarkerValueWith @SpecUnion contract) (Aeson.object ["kind" Aeson..= ("missing" :: Text)]) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractMarkerValueWith @SpecUnion contract) (Aeson.object ["kind" Aeson..= ("one" :: Text), "value" Aeson..= goodNested, "extra" Aeson..= True]) `shouldSatisfy` isLeft

    it "validates semantic scope and fragment-key wire constructors without executable descriptors" do
        let scope = Aeson.object ["surface" Aeson..= ("timesheets" :: Text), "scope" Aeson..= Aeson.object ["venueId" Aeson..= ("11111111-1111-1111-1111-111111111111" :: Text), "weekOffset" Aeson..= (0 :: Int)]]
        let key = Aeson.object ["surface" Aeson..= ("timesheets" :: Text), "kind" Aeson..= ("timesheet-day-section" :: Text), "params" Aeson..= Aeson.object ["dayOffset" Aeson..= (0 :: Int)]]
        let descriptor = addJsonField "url" (Aeson.String "/fragment") key
        AesonTypes.parseEither (validateWireValue "scope" Contract.WireSurfaceScopeIR) scope `shouldSatisfy` isRight
        AesonTypes.parseEither (validateWireValue "key" Contract.WireSurfaceFragmentKeyIR) key `shouldSatisfy` isRight
        AesonTypes.parseEither (validateWireValue "scope" Contract.WireSurfaceScopeIR) (addJsonField "extra" (Aeson.Bool True) scope) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateWireValue "key" Contract.WireSurfaceFragmentKeyIR) (replaceJsonField "kind" (Aeson.String "missing") key) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateWireValue "key" Contract.WireSurfaceFragmentKeyIR) descriptor `shouldSatisfy` isLeft

    it "generates codecs only for their declared browser reachability" do
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export function parseLiveUpdateMessage"
        frontendContractsTypeScript `shouldNotSatisfy` Text.isInfixOf "export function encodeLiveUpdateMessage"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export function encodeLiveUpdateCommand"
        frontendContractsTypeScript `shouldNotSatisfy` Text.isInfixOf "export function parseLiveUpdateCommand"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export function isRosterStaffSortKey"
        frontendContractsTypeScript `shouldNotSatisfy` Text.isInfixOf "export function parseRosterStaffSortKey"
        frontendContractsTypeScript `shouldNotSatisfy` Text.isInfixOf "export function encodeRosterStaffSortKey"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export function parseFrontendSurfaceMountConfig"
        frontendContractsTypeScript `shouldNotSatisfy` Text.isInfixOf "export function encodeFrontendSurfaceMountConfig"

    it "renders separate minimal fragment and interaction runtime registries" do
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export const FrontendSurfaceFragmentRegistry"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export const FrontendSurfaceInteractionRegistry"
        frontendContractsTypeScript `shouldNotSatisfy` Text.isInfixOf "export const FrontendSurfaceRegistry"
        frontendContractsTypeScript `shouldNotSatisfy` Text.isInfixOf "InteractionStaticSchemas"
        frontendContractsTypeScript `shouldNotSatisfy` Text.isInfixOf "htmxActions"
        frontendContractsTypeScript `shouldNotSatisfy` Text.isInfixOf "containedSurfaces"
        frontendContractsTypeScript `shouldNotSatisfy` Text.isInfixOf "FrontendSurfaceActionManifest"
        frontendContractsTypeScript `shouldNotSatisfy` Text.isInfixOf "timesheetsSurfaceManifest"

generatedContractTypeNames :: Text -> [Text]
generatedContractTypeNames source =
    [ Text.takeWhile (/= ' ') rest
    | line <- Text.lines source
    , Just rest <- [Text.stripPrefix "export type " line]
    ]

wireJsonSpecContract :: Contract.FrontendContractIR
wireJsonSpecContract =
    Contract.FrontendContractIR
        { contractGlobals =
            [ Contract.GlobalIR
                { globalMarker = "SpecGlobal"
                , globalName = "spec-global"
                , globalPrimitives = fmap (Contract.GlobalSchemaIR Contract.BrowserBidirectionalIR)
                    [ Contract.EnumIR "SpecStatus" "SpecStatus" ["ready", "paused"]
                    , Contract.LiteralEnumIR "SpecLiteral" "SpecLiteral" [("SpecialCase", "special-case")]
                    , Contract.RecordIR "SpecNested" "SpecNested"
                        [ field "Name" "name" Contract.WireTextIR Contract.RequiredField
                        , field "Count" "count" Contract.WireIntIR Contract.RequiredField
                        , field "Active" "active" Contract.WireBoolIR Contract.RequiredField
                        , field "Uuid" "uuid" Contract.WireUuidIR Contract.RequiredField
                        , field "Day" "day" Contract.WireDayIR Contract.RequiredField
                        , field "Tags" "tags" (Contract.WireListIR Contract.WireTextIR) Contract.RequiredField
                        , field "MaybeText" "maybeText" (Contract.WireOptionalIR Contract.WireTextIR) Contract.OptionalFieldPresence
                        , field "NullableText" "nullableText" (Contract.WireNullableIR Contract.WireTextIR) Contract.NullableFieldPresence
                        , field "Status" "status" (Contract.WireRefIR "SpecStatus") Contract.RequiredField
                        , field "Literal" "literal" (Contract.WireRefIR "SpecLiteral") Contract.RequiredField
                        ]
                    , Contract.RecordIR "SpecRecord" "SpecRecord"
                        [ field "Nested" "nested" (Contract.WireRefIR "SpecNested") Contract.RequiredField
                        , field "Items" "items" (Contract.WireListIR (Contract.WireRefIR "SpecNested")) Contract.RequiredField
                        ]
                    , Contract.TaggedUnionIR "SpecUnion" "SpecUnion" "kind"
                        [ Contract.UnionCaseIR "One" "one" [field "Value" "value" (Contract.WireRefIR "SpecNested") Contract.RequiredField]
                        , Contract.UnionCaseIR "Two" "two" [field "Note" "note" Contract.WireTextIR Contract.RequiredField]
                        ]
                    ]
                }
            ]
        , contractSurfaces = []
        }
    where
        field marker name wire presence =
            Contract.FieldIR
                { fieldMarker = marker
                , fieldName = name
                , fieldWire = wire
                , fieldPresence = presence
                }

addJsonField :: Text -> Aeson.Value -> Aeson.Value -> Aeson.Value
addJsonField name value = \case
    Aeson.Object object -> Aeson.Object (KeyMap.insert (AesonKey.fromText name) value object)
    other               -> other

removeJsonField :: Text -> Aeson.Value -> Aeson.Value
removeJsonField name = \case
    Aeson.Object object -> Aeson.Object (KeyMap.delete (AesonKey.fromText name) object)
    other               -> other

replaceJsonField :: Text -> Aeson.Value -> Aeson.Value -> Aeson.Value
replaceJsonField name value = \case
    Aeson.Object object -> Aeson.Object (KeyMap.insert (AesonKey.fromText name) value object)
    other               -> other
