{-# LANGUAGE LambdaCase          #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE TypeApplications    #-}

module Test.FrontendContractsSpec
    ( tests
    ) where

import qualified Application.Helper.FrontendContract.App as App
import qualified Application.Helper.FrontendContract.AppShell as AppShell
import Application.Helper.FrontendContract.AppShell.Runtime (AppShellActionRoute (..),
                                                             appShellActionByMarker,
                                                             appShellActionHtmxAttrPairs)
import Application.Helper.FrontendContract.AppValues (AppEvents (..),
                                                      AppOverlayDom (..),
                                                      canonicalAppEvents,
                                                      canonicalAppOverlayDom,
                                                      interactionIntentSubmitHtmxTrigger,
                                                      sharedDialogOverlayMountId,
                                                      sharedToastOverlayMountId)
import Application.Helper.FrontendContract.Contracts (TypeScriptDeclaration (..),
                                                      TypeScriptDeclarationOrigin (..),
                                                      frontendContractDeclarations,
                                                      frontendContractsTypeScript)
import qualified Application.Helper.FrontendContract.Htmx as Htmx
import qualified Application.Helper.FrontendContract.IR as Contract
import Application.Helper.FrontendContract.Registry (registeredFrontendContractIR)
import Application.Helper.FrontendContract.RosterValues (RosterStaffSortKey (..),
                                                         rosterStaffSortKeyAttribute,
                                                         rosterStaffSortKeyValues)
import qualified Application.Helper.FrontendContract.Surface.ContractIR as SurfaceIR
import Application.Helper.FrontendContract.Values (domIdValue, enumLiteralValue,
                                                   eventNameValue,
                                                   lookupDomIdValue,
                                                   lookupEnumLiteralValue,
                                                   lookupEventNameValue)
import Application.Helper.FrontendContract.Wire.Json (validateContractValue,
                                                      validateContractValueWith,
                                                      validateSurfaceFragmentKeyValue,
                                                      validateSurfaceScopeValue,
                                                      validateWireValue)
import qualified Application.Helper.FrontendContract.Wire.LiveUpdate as Live
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as KeyMap
import qualified Data.Aeson.Types as AesonTypes
import qualified Data.ByteString.Lazy as LBS
import Data.Either (isLeft, isRight)
import qualified Data.List as List
import qualified Data.Text as Text
import qualified Data.Text.Encoding as TextEncoding
import qualified Data.Text.IO as Text
import IHP.Prelude
import System.Directory (doesDirectoryExist, listDirectory)
import System.FilePath (takeExtension, (</>))
import Test.Hspec

tests :: Spec
tests = describe "Frontend contract generator foundation" do
    it "keeps the public generated file entrypoint FrontendContract-owned" do
        frontendContractsTypeScript `shouldSatisfy` Text.isPrefixOf "// @generated by Application.Helper.FrontendContract.Contracts"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export type OverlayLane"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export type SurfaceScope"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export type LiveUpdateCommand"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export type UiRegionTransitionProfile"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export type InteractionSessionEffect"

    it "registers one generated FrontendContract declaration block" do
        [(declaration.name, declaration.origin) | declaration <- frontendContractDeclarations]
            `shouldBe` [("FrontendContractGlobals", HaskellSchemaGenerated)]

    it "keeps the composition root free of handwritten protocol blocks" do
        source <- Text.readFile "Application/Helper/FrontendContract/Contracts.hs"
        source `shouldNotSatisfy` Text.isInfixOf "export type SurfaceScope"
        source `shouldNotSatisfy` Text.isInfixOf "export const InteractionDom"
        source `shouldNotSatisfy` Text.isInfixOf "export type UiRegionTransitionProfile"

    it "uses one shared HTMX metadata model for generated request primitives" do
        let genericOptions =
                [ Contract.HtmxActionMethodIR "post"
                , Contract.HtmxActionTriggerIR "change"
                , Contract.HtmxActionIncludeIR "#filters"
                , Contract.HtmxActionSyncIR "closest form:queue"
                , Contract.HtmxActionIndicatorIR "#spinner"
                , Contract.HtmxActionConfirmIR "Continue?"
                , Contract.HtmxActionSelectIR "#fragment"
                , Contract.HtmxActionTargetIR "target"
                , Contract.HtmxActionSwapIR "outerHTML"
                , Contract.HtmxActionPushUrlIR False
                , Contract.HtmxActionCustomHtmxIR "custom-marker" "fixture escape hatch"
                ]
        let surfaceOptions =
                [ SurfaceIR.HtmxMethodOption SurfaceIR.HtmxPostIR
                , SurfaceIR.HtmxTriggerOption "change"
                , SurfaceIR.HtmxIncludeOption "#filters"
                , SurfaceIR.HtmxSyncOption "closest form:queue"
                , SurfaceIR.HtmxIndicatorOption "#spinner"
                , SurfaceIR.HtmxConfirmOption "Continue?"
                , SurfaceIR.HtmxSelectOption "#fragment"
                , SurfaceIR.HtmxTargetOption "target"
                , SurfaceIR.HtmxSwapOption "outerHTML"
                , SurfaceIR.HtmxPushUrlOption SurfaceIR.HtmxPushUrlFalseIR
                , SurfaceIR.CustomHtmxOption "custom-marker" "fixture escape hatch"
                ]
        let metadata = Htmx.htmxActionMetadataFromOptions genericOptions
        metadata `shouldBe` Htmx.htmxActionMetadataFromSurfaceOptions surfaceOptions
        Htmx.htmxActionOptionAttrPairs metadata
            `shouldBe` [ ("hx-trigger", "change")
                       , ("hx-include", "#filters")
                       , ("hx-sync", "closest form:queue")
                       , ("hx-indicator", "#spinner")
                       , ("hx-confirm", "Continue?")
                       , ("hx-select", "#fragment")
                       , ("hx-target", "#target")
                       , ("hx-swap", "outerHTML")
                       , ("hx-push-url", "false")
                       ]
        Htmx.htmxActionConfigJson "fixture-action" ["fieldOne"] metadata
            `shouldSatisfy` Text.isInfixOf "\"method\":\"post\""

    it "reflects generated AppShell action manifests and runtime attrs" do
        let appShellActions =
                [ action
                | global <- registeredFrontendContractIR.contractGlobals
                , Contract.GlobalAppShellActionIR action <- global.globalPrimitives
                ]
        let partialNavigateAction = appShellActionByMarker @AppShell.PartialNavigate
        let openFeedbackDialogAction = appShellActionByMarker @AppShell.OpenFeedbackDialog
        fmap (.appShellActionName) (find ((== "partial-navigate") . (.appShellActionName)) appShellActions) `shouldBe` Just "partial-navigate"
        partialNavigateAction.appShellActionOptions
            `shouldBe` [ Contract.HtmxActionMethodIR "get"
                       , Contract.HtmxActionCustomHtmxIR "partial-navigation-htmx-attrs" "partial navigation supplies route-specific target, swap, select, push-url, and sync attrs"
                       ]
        openFeedbackDialogAction.appShellActionOptions
            `shouldBe` [ Contract.HtmxActionMethodIR "get"
                       , Contract.HtmxActionTargetIR "dialog-overlay-mount"
                       , Contract.HtmxActionSwapIR "innerHTML"
                       , Contract.HtmxActionPushUrlIR False
                       ]
        appShellActionHtmxAttrPairs partialNavigateAction AppShellActionRoute
            { appShellActionRouteUrl = "/next"
            , appShellActionRouteFields = []
            , appShellActionRouteCustomHtmx = []
            , appShellActionRouteStandardUrl = Nothing
            , appShellActionRouteExtraAttrs = []
            }
            `shouldContain` [("data-bepis-app-shell-action", "partial-navigate")]
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export type AppShellActionManifest"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export const partialNavigateAppShellActionManifest"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export const openFeedbackDialogAppShellActionManifest"

    it "reflects generated app shell action manifests" do
        let appShellActions =
                [ action
                | global <- registeredFrontendContractIR.contractGlobals
                , Contract.GlobalAppShellActionIR action <- global.globalPrimitives
                ]
        let openFeedbackAction = find ((== "open-feedback-dialog") . (.appShellActionName)) appShellActions
        fmap (.appShellActionFields) openFeedbackAction `shouldBe` Just []
        fmap (.appShellActionOptions) openFeedbackAction
            `shouldBe` Just
                [ Contract.HtmxActionMethodIR "get"
                , Contract.HtmxActionTargetIR "dialog-overlay-mount"
                , Contract.HtmxActionSwapIR "innerHTML"
                , Contract.HtmxActionPushUrlIR False
                ]
        let submitFeedbackAction = find ((== "submit-feedback") . (.appShellActionName)) appShellActions
        fmap (fmap (.fieldName) . (.appShellActionFields)) submitFeedbackAction `shouldBe` Just ["feedbackType", "content"]
        fmap (.appShellActionOptions) submitFeedbackAction
            `shouldBe` Just
                [ Contract.HtmxActionMethodIR "post"
                , Contract.HtmxActionTargetIR "dialog-overlay-mount"
                , Contract.HtmxActionSwapIR "innerHTML"
                , Contract.HtmxActionPushUrlIR False
                ]

    it "exposes consistent Profile and Staff surface profile action field sets" do
        let surfaceActions surfaceName actionName =
                [ action
                | surface <- registeredFrontendContractIR.contractSurfaces
                , surface.surfaceName == surfaceName
                , Contract.SurfaceActionIR _ action _ _ <- surface.surfacePrimitives
                , action == actionName
                ]
        let actionFields surfaceName actionName =
                [ fields
                | surface <- registeredFrontendContractIR.contractSurfaces
                , surface.surfaceName == surfaceName
                , Contract.SurfaceActionIR _ action fields _ <- surface.surfacePrimitives
                , action == actionName
                ]
        surfaceActions "staff" "update-staff-profile" `shouldBe` ["update-staff-profile"]
        actionFields "profile" "update-profile-details" `shouldBe` actionFields "staff" "update-staff-profile"
        actionFields "profile" "update-profile-shift-preferences" `shouldBe` actionFields "staff" "update-staff-shift-preferences"
        frontendContractsTypeScript `shouldSatisfy` Text.isInfixOf "export const staffSurfaceManifest"

    it "keeps migrated feedback overlay openers on generated AppShellAction helpers" do
        source <- Text.readFile "Web/View/Layout.hs"
        source `shouldSatisfy` Text.isInfixOf "appShellActionByMarker @OpenFeedbackDialog"
        source `shouldNotSatisfy` Text.isInfixOf "appShellActionByName \"open-feedback-dialog\""
        source `shouldNotSatisfy` Text.isInfixOf "hx-get={NewFeedbackAction}"

    it "resolves canonical Haskell value accessors from registered FrontendContract IR" do
        lookupDomIdValue @App.DialogOverlayMount `shouldBe` Right sharedDialogOverlayMountId
        lookupDomIdValue @App.ToastOverlayMount `shouldBe` Right sharedToastOverlayMountId
        lookupEventNameValue @App.IntentSubmit `shouldBe` Right interactionIntentSubmitHtmxTrigger
        lookupEnumLiteralValue @App.RosterStaffSortKey @App.Name `shouldBe` Right "name"
        domIdValue @App.DialogOverlayMount `shouldBe` canonicalAppOverlayDom.appDialogOverlayMountId
        eventNameValue @App.IntentSubmit `shouldBe` canonicalAppEvents.appInteractionIntentSubmitEventName
        enumLiteralValue @App.RosterStaffSortKey @App.Name `shouldBe` rosterStaffSortKeyAttribute RosterStaffSortByName
        rosterStaffSortKeyValues
            `shouldBe` [ (RosterStaffSortByName, "name")
                       , (RosterStaffSortByRole, "role")
                       , (RosterStaffSortByShifts, "shifts")
                       ]

    it "returns deterministic diagnostics for missing Haskell value accessors" do
        lookupDomIdValue @Text `shouldBe` Left "No FrontendContract DomId declaration for marker Text"
        lookupEventNameValue @Text `shouldBe` Left "No FrontendContract Event declaration for marker Text"
        lookupEnumLiteralValue @Text @Text `shouldBe` Left "No FrontendContract enum case Text for enum marker Text"

    it "validates records, refs, arrays, nullable fields, and tagged unions through the IR JSON interpreter" do
        let scope = Live.SurfaceScope "timesheets" (Aeson.object ["venueId" Aeson..= ("11111111-1111-1111-1111-111111111111" :: Text), "weekOffset" Aeson..= (4 :: Int)])
        let fragment = Live.SurfaceWireFragment
                (Live.SurfaceFragmentKey "timesheets" "timesheet-day-section" (Aeson.object ["dayOffset" Aeson..= (2 :: Int)]))
                "timesheet-day-2"
                "/TimesheetDay?offset=2"
                True
                (Live.FocusedFieldProtection ".timesheet-input:focus" "data-field-key" True (Just ".timesheet-row"))
        let subscription = Live.SurfaceSubscription scope "timesheets:11111111-1111-1111-1111-111111111111:4" [fragment]
        let command = Live.Subscribe subscription "client-1" (Just 9)
        let message = Live.Invalidate scope "timesheets:11111111-1111-1111-1111-111111111111:4" 10 [fragment] (Just "client-2")

        AesonTypes.parseEither (validateContractValue "SurfaceSubscription") (Aeson.toJSON subscription) `shouldSatisfy` isRight
        AesonTypes.parseEither (validateContractValue "LiveUpdateCommand") (Aeson.toJSON command) `shouldSatisfy` isRight
        AesonTypes.parseEither (validateContractValue "LiveUpdateMessage") (Aeson.toJSON message) `shouldSatisfy` isRight
        Aeson.eitherDecode (Aeson.encode command) `shouldBe` Right command
        Aeson.eitherDecode (Aeson.encode message) `shouldBe` Right message

    it "rejects invalid surface scopes, fragments, enum values, and union discriminators through the IR JSON interpreter" do
        let badScope = Aeson.object ["surface" Aeson..= ("missing" :: Text), "scope" Aeson..= Aeson.object []]
        let badFragment = Aeson.object ["surface" Aeson..= ("timesheets" :: Text), "kind" Aeson..= ("missing" :: Text), "params" Aeson..= Aeson.object []]
        let badProtection = Aeson.object ["kind" Aeson..= ("missing" :: Text)]
        let badCommand = Aeson.object ["type" Aeson..= ("missing" :: Text)]

        AesonTypes.parseEither validateSurfaceScopeValue badScope `shouldSatisfy` isLeft
        AesonTypes.parseEither validateSurfaceFragmentKeyValue badFragment `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractValue "SurfaceFragmentProtection") badProtection `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractValue "LiveUpdateCommand") badCommand `shouldSatisfy` isLeft

    it "covers Wire.Json field presence, nested refs, arrays, enums, and tagged unions" do
        let contract = wireJsonSpecContract
        let goodNested = Aeson.object
                [ "name" Aeson..= ("Ada" :: Text)
                , "count" Aeson..= (3 :: Int)
                , "active" Aeson..= True
                , "uuid" Aeson..= ("not-a-uuid-but-contract-string" :: Text)
                , "day" Aeson..= ("not-a-day-but-contract-string" :: Text)
                , "tags" Aeson..= (["alpha", "beta"] :: [Text])
                , "maybeText" Aeson..= Aeson.Null
                , "nullableText" Aeson..= Aeson.Null
                , "status" Aeson..= ("ready" :: Text)
                , "literal" Aeson..= ("special-case" :: Text)
                ]
        let goodRecord = Aeson.object
                [ "nested" Aeson..= goodNested
                , "items" Aeson..= [goodNested]
                ]
        AesonTypes.parseEither (validateContractValueWith contract "SpecRecord") goodRecord `shouldSatisfy` isRight
        AesonTypes.parseEither (validateContractValueWith contract "SpecUnion") (Aeson.object ["kind" Aeson..= ("one" :: Text), "value" Aeson..= goodNested]) `shouldSatisfy` isRight
        AesonTypes.parseEither (validateContractValueWith contract "SpecUnion") (Aeson.object ["kind" Aeson..= ("two" :: Text), "note" Aeson..= ("ok" :: Text)]) `shouldSatisfy` isRight
        AesonTypes.parseEither (validateWireValue "uuid" Contract.WireUuidIR) (Aeson.String "not-a-uuid-but-contract-string") `shouldSatisfy` isRight
        AesonTypes.parseEither (validateWireValue "day" Contract.WireDayIR) (Aeson.String "not-a-day-but-contract-string") `shouldSatisfy` isRight

        AesonTypes.parseEither (validateContractValueWith contract "SpecNested") (addJsonField "extra" (Aeson.Bool True) goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractValueWith contract "SpecNested") (removeJsonField "name" goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractValueWith contract "SpecNested") (removeJsonField "maybeText" goodNested) `shouldSatisfy` isRight
        AesonTypes.parseEither (validateContractValueWith contract "SpecNested") (removeJsonField "nullableText" goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractValueWith contract "SpecNested") (replaceJsonField "name" (Aeson.Number 1) goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractValueWith contract "SpecNested") (replaceJsonField "count" (Aeson.Number 1.5) goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractValueWith contract "SpecNested") (replaceJsonField "tags" (Aeson.String "alpha") goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractValueWith contract "SpecNested") (replaceJsonField "status" (Aeson.String "missing") goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractValueWith contract "SpecNested") (replaceJsonField "literal" (Aeson.String "case") goodNested) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractValueWith contract "SpecRecord") (replaceJsonField "nested" (Aeson.object []) goodRecord) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractValueWith contract "SpecUnion") (Aeson.object ["kind" Aeson..= ("missing" :: Text)]) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateContractValueWith contract "SpecUnion") (Aeson.object ["kind" Aeson..= ("one" :: Text), "value" Aeson..= goodNested, "extra" Aeson..= True]) `shouldSatisfy` isLeft

    it "validates surface scope, fragment key, and SurfaceWireFragment wire constructors" do
        let scope = Aeson.object ["surface" Aeson..= ("timesheets" :: Text), "scope" Aeson..= Aeson.object ["venueId" Aeson..= ("11111111-1111-1111-1111-111111111111" :: Text), "weekOffset" Aeson..= (0 :: Int)]]
        let key = Aeson.object ["surface" Aeson..= ("timesheets" :: Text), "kind" Aeson..= ("timesheet-day-section" :: Text), "params" Aeson..= Aeson.object ["dayOffset" Aeson..= (0 :: Int)]]
        let fragment = Aeson.object
                [ "fragmentKey" Aeson..= key
                , "targetId" Aeson..= ("target" :: Text)
                , "url" Aeson..= ("/fragment" :: Text)
                , "deferUntilBlur" Aeson..= True
                , "protectionPolicy" Aeson..= Aeson.object ["kind" Aeson..= ("none" :: Text)]
                ]
        AesonTypes.parseEither (validateWireValue "scope" Contract.WireSurfaceScopeIR) scope `shouldSatisfy` isRight
        AesonTypes.parseEither (validateWireValue "key" Contract.WireSurfaceFragmentKeyIR) key `shouldSatisfy` isRight
        AesonTypes.parseEither (validateWireValue "fragment" Contract.WireSurfaceWireFragmentIR) fragment `shouldSatisfy` isRight
        AesonTypes.parseEither (validateWireValue "scope" Contract.WireSurfaceScopeIR) (addJsonField "extra" (Aeson.Bool True) scope) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateWireValue "key" Contract.WireSurfaceFragmentKeyIR) (replaceJsonField "kind" (Aeson.String "missing") key) `shouldSatisfy` isLeft
        AesonTypes.parseEither (validateWireValue "fragment" Contract.WireSurfaceWireFragmentIR) (removeJsonField "url" fragment) `shouldSatisfy` isLeft

    it "keeps generated contract validators, parsers, and encoders out of handwritten TypeScript" do
        offenders <- frontendGeneratedHelperOffenders (generatedContractTypeNames frontendContractsTypeScript)
        offenders `shouldBe` []

    it "keeps canonical generated strings out of handwritten frontend runtime" do
        offenders <- canonicalStringOffendersWithAllowedPrefixes
            ["frontend/ts"]
            [ "frontend/ts/generated/contracts.ts"
            , "frontend/ts/app-live-updates.ts"
            , "frontend/ts/live-updates/frontend-surface.ts"
            ]
            ["frontend/ts/tests/"]
            [".ts"]
            frontendRuntimeGeneratedOnlyStrings
        offenders `shouldBe` []

    it "has no legacy Frontend helper contract authorities" do
        frontendExists <- doesDirectoryExist "Application/Helper/Frontend"
        files <- if frontendExists then collectSourceFiles "Application/Helper/Frontend" else pure []
        files `shouldBe` []

    it "locks down raw TypeScript emitters to FrontendContract renderer internals only" do
        files <- collectSourceFiles "Application/Helper/FrontendContract"
        offenders <- fmap concat $ forM files \path -> do
            source <- Text.readFile path
            pure
                [ (path, pattern)
                | path /= "Application/Helper/FrontendContract/TypeScript.hs"
                , path /= "Application/Helper/FrontendContract/Contracts.hs"
                , pattern <- rawEmitterPatterns
                , pattern `Text.isInfixOf` source
                ]
        offenders `shouldBe` []

generatedContractTypeNames :: Text -> [Text]
generatedContractTypeNames source =
    [ Text.takeWhile (/= ' ') rest
    | line <- Text.lines source
    , Just rest <- [Text.stripPrefix "export type " line]
    ]

frontendGeneratedHelperOffenders :: [Text] -> IO [(FilePath, Text)]
frontendGeneratedHelperOffenders typeNames = do
    files <- collectSourceFiles "frontend/ts"
    fmap concat $ forM files \path -> do
        if path `elem` ["frontend/ts/generated/contracts.ts", "frontend/ts/live-updates/frontend-surface.ts"]
            then pure []
            else do
                source <- Text.readFile path
                pure
                    [ (path, helper)
                    | typeName <- typeNames
                    , prefix <- ["is", "parse", "encode"]
                    , let helper = prefix <> typeName
                    , any (`Text.isInfixOf` source)
                        [ "function " <> helper
                        , "const " <> helper
                        , "let " <> helper
                        , "var " <> helper
                        ]
                    ]

frontendRuntimeGeneratedOnlyStrings :: [Text]
frontendRuntimeGeneratedOnlyStrings =
    [ "data-bepis-"
    , "bepis:page-ready"
    , "bepis:live-fragments-refresh"
    , "bepis:interaction-intent"
    , "bepis:intent-submit"
    , "bepis:interaction-session-start"
    , "bepis:interaction-session-end"
    , "bepis:interaction-session-cancel-request"
    ]

canonicalStringOffendersWithAllowedPrefixes :: [FilePath] -> [FilePath] -> [FilePath] -> [FilePath] -> [Text] -> IO [(FilePath, Text)]
canonicalStringOffendersWithAllowedPrefixes roots allowedFiles allowedPrefixes extensions needles = do
    files <- fmap List.sort (concat <$> mapM collectSourceFiles roots)
    fmap concat $ forM files \path -> do
        if path `elem` allowedFiles || any (`List.isPrefixOf` path) allowedPrefixes || takeExtension path `notElem` extensions
            then pure []
            else do
                source <- Text.readFile path
                pure [(path, needle) | needle <- needles, needle `Text.isInfixOf` source]

rawEmitterPatterns :: [Text]
rawEmitterPatterns =
    [ "TSRawDeclaration"
    , "\"export type"
    , "\"export interface"
    , "\"export const"
    , "\"export function"
    , "stringUnionDeclaration"
    ]

wireJsonSpecContract :: Contract.FrontendContractIR
wireJsonSpecContract =
    Contract.FrontendContractIR
        { contractGlobals =
            [ Contract.GlobalIR
                { globalMarker = "SpecGlobal"
                , globalName = "spec-global"
                , globalPrimitives = fmap Contract.GlobalSchemaIR
                    [ Contract.EnumIR "SpecStatus" "SpecStatus" ["ready", "paused"]
                    , Contract.LiteralEnumIR "SpecLiteral" "SpecLiteral" [("SpecialCase", "special-case")]
                    , Contract.RecordIR "SpecNested" "SpecNested"
                        [ field "Name" "name" Contract.WireTextIR Contract.RequiredField
                        , field "Count" "count" Contract.WireIntIR Contract.RequiredField
                        , field "Active" "active" Contract.WireBoolIR Contract.RequiredField
                        , field "Uuid" "uuid" Contract.WireUuidIR Contract.RequiredField
                        , field "Day" "day" Contract.WireDayIR Contract.RequiredField
                        , field "Tags" "tags" (Contract.WireListIR Contract.WireTextIR) Contract.RequiredField
                        , field "MaybeText" "maybeText" (Contract.WireOptionalIR Contract.WireTextIR) Contract.OptionalFieldPresence
                        , field "NullableText" "nullableText" (Contract.WireNullableIR Contract.WireTextIR) Contract.NullableFieldPresence
                        , field "Status" "status" (Contract.WireRefIR "SpecStatus") Contract.RequiredField
                        , field "Literal" "literal" (Contract.WireRefIR "SpecLiteral") Contract.RequiredField
                        ]
                    , Contract.RecordIR "SpecRecord" "SpecRecord"
                        [ field "Nested" "nested" (Contract.WireRefIR "SpecNested") Contract.RequiredField
                        , field "Items" "items" (Contract.WireListIR (Contract.WireRefIR "SpecNested")) Contract.RequiredField
                        ]
                    , Contract.TaggedUnionIR "SpecUnion" "SpecUnion" "kind"
                        [ Contract.UnionCaseIR "One" "one" [field "Value" "value" (Contract.WireRefIR "SpecNested") Contract.RequiredField]
                        , Contract.UnionCaseIR "Two" "two" [field "Note" "note" Contract.WireTextIR Contract.RequiredField]
                        ]
                    ]
                }
            ]
        , contractSurfaces = []
        }
    where
        field marker name wire presence =
            Contract.FieldIR
                { fieldMarker = marker
                , fieldName = name
                , fieldWire = wire
                , fieldPresence = presence
                }

addJsonField :: Text -> Aeson.Value -> Aeson.Value -> Aeson.Value
addJsonField name value = \case
    Aeson.Object object -> Aeson.Object (KeyMap.insert (AesonKey.fromText name) value object)
    other               -> other

removeJsonField :: Text -> Aeson.Value -> Aeson.Value
removeJsonField name = \case
    Aeson.Object object -> Aeson.Object (KeyMap.delete (AesonKey.fromText name) object)
    other               -> other

replaceJsonField :: Text -> Aeson.Value -> Aeson.Value -> Aeson.Value
replaceJsonField name value = \case
    Aeson.Object object -> Aeson.Object (KeyMap.insert (AesonKey.fromText name) value object)
    other               -> other

collectSourceFiles :: FilePath -> IO [FilePath]
collectSourceFiles root = do
    exists <- doesDirectoryExist root
    if not exists
        then pure []
        else go root
    where
        go path = do
            entries <- listDirectory path
            fmap concat $ forM entries \entry -> do
                let child = path </> entry
                isDirectory <- doesDirectoryExist child
                if isDirectory
                    then go child
                    else pure [child | takeExtension child `elem` [".hs", ".ts"]]
