{-# LANGUAGE DataKinds           #-}
{-# LANGUAGE LambdaCase          #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE TypeApplications    #-}

-- | Focused checked-IR projection for private generated Surface resource
-- adapters. Shared validation and module mechanics live in 'Core'; this module
-- owns only resource eligibility, names, imports, and public builder/matcher
-- source shapes.
module Application.Helper.FrontendContract.Surface.HaskellAdapter.Resource
    ( generateSurfaceResourceAdapterModules
    ) where

import Application.Helper.FrontendContract.Naming (wordsFromTypeName)
import Application.Helper.FrontendContract.Surface.ContractIR
import Application.Helper.FrontendContract.Surface.HaskellAdapter.Core
import Application.Helper.FrontendContract.Surface.HaskellAdapter.Family
import qualified Data.List as List
import qualified Data.Map.Strict as Map
import qualified Data.Text as Text
import IHP.Prelude

generateSurfaceResourceAdapterModules ::
    SurfaceContractIR ->
    SurfaceAdapterRegistry ->
    Either [ContractDiagnostic] [GeneratedHaskellModule]
generateSurfaceResourceAdapterModules contract registry = do
    adapters <-
        resolveAdapterGeneration
            resourceAdapterLayout
            contract
            registry.surfaceAdapterFamilies
            registry.surfaceResourceAdapterHomes
            (resourceAdapterDeclarations contract)
            resourceGeneratedNames
    renderGeneratedAdapterModules
        resourceModuleRenderer
        (map (toRenderableAdapter id) adapters)

resourceAdapterDeclarations :: SurfaceContractIR -> [CheckedAdapterDeclaration 'ResourceAdapterKind ResourceIR]
resourceAdapterDeclarations contract =
    [ CheckedAdapterDeclaration
        { checkedAdapterIdentity = resourceAdapterIdentity resource.resourceName
        , checkedAdapterSurfaceMarker = surface.surfaceMarker
        , checkedAdapterSurfaceName = surface.surfaceName
        , checkedAdapterDeclarationMarker = resource.resourceMarker
        , checkedAdapterDeclarationName = resource.resourceName
        , checkedAdapterFields = resource.resourceFields
        , checkedAdapterPayload = resource
        }
    | surface <- contract.contractSurfaces
    , resource <- resourcesForSurface surface
    ]

resourceGeneratedNames :: CheckedAdapterDeclaration 'ResourceAdapterKind ResourceIR -> [Text]
resourceGeneratedNames declaration =
    [ constructorName
    , "match" <> upperFirst constructorName
    ]
  where
    constructorName = resourceConstructorName declaration.checkedAdapterDeclarationMarker

resourceModuleRenderer :: AdapterModuleRenderer ResourceIR
resourceModuleRenderer =
    AdapterModuleRenderer
        { adapterRendererLanguagePragmas = ["{-# LANGUAGE TypeApplications #-}"]
        , adapterRendererHeaderLines =
            [ "-- @generated by Application.Helper.FrontendContract.Surface.HaskellAdapter.Generator"
            , "-- Do not edit; run `bash ./bin/in-env frontend-surface-adapters`."
            ]
        , adapterRendererImports = renderResourceImports
        , adapterRendererDeclaration = renderResourceAdapter
        }

renderResourceImports ::
    Map.Map Text Text ->
    [RenderableAdapter ResourceIR] ->
    [Text]
renderResourceImports aliases adapters =
    renderImportList
        "Application.Helper.FrontendContract.Surface.HaskellAdapter.Family"
        ["AdapterFamilySurface"]
        <> renderImportList
            "Application.Helper.FrontendContract.Surface.Resource"
            [ "SurfaceResourceValue"
            , "frontendSurfaceResource"
            , "matchFrontendSurfaceResource"
            ]
        <> renderImportList
            "Application.Helper.FrontendContract.Surface.Values"
            valueImports
        <> conditionalImport needsDay "import Data.Time (Day)"
        <> conditionalImport needsUuid "import qualified Data.UUID as UUID"
        <> ["import IHP.Prelude"]
        <> [ "import qualified " <> sourceModule <> " as " <> alias
           | (sourceModule, alias) <- Map.toAscList aliases
           ]
  where
    fields = concatMap (.renderableAdapterFields) adapters
    valueImports =
        [ if null fields
            then "SurfaceFields (NoSurfaceFields)"
            else "SurfaceFields (NoSurfaceFields, (:&))"
        ]
            <> ["surfaceField" | any ((== RequiredField) . (.fieldPresence) . (.resolvedAdapterFieldIR)) fields]
            <> ["surfaceNullableField" | any ((== NullableFieldPresence) . (.fieldPresence) . (.resolvedAdapterFieldIR)) fields]
            <> ["surfaceOptionalField" | any ((== OptionalFieldPresence) . (.fieldPresence) . (.resolvedAdapterFieldIR)) fields]
    allTypes = concatMap (map (.resolvedAdapterFieldType) . (.renderableAdapterFields)) adapters
    needsDay = any sourceTypeContainsDay allTypes
    needsUuid = any sourceTypeContainsUuid allTypes
    conditionalImport True line = [line]
    conditionalImport False _   = []

renderResourceAdapter ::
    Map.Map Text Text ->
    RenderableAdapter ResourceIR ->
    [Text]
renderResourceAdapter aliases adapter =
    renderConstructorSignature adapter
        <> renderConstructorBody aliases adapter
        <> [""]
        <> renderMatcherSignature adapter
        <> renderMatcherBody aliases adapter

renderConstructorSignature :: RenderableAdapter ResourceIR -> [Text]
renderConstructorSignature adapter =
    case adapter.renderableAdapterFields of
        [] -> [resolvedConstructor adapter <> " :: SurfaceResourceValue"]
        fields ->
            [resolvedConstructor adapter <> " ::"]
                <> map ("    " <>)
                    ( map ((<> " ->") . renderHaskellSourceType . (.resolvedAdapterFieldType)) fields
                        <> ["SurfaceResourceValue"]
                    )

renderConstructorBody ::
    Map.Map Text Text ->
    RenderableAdapter ResourceIR ->
    [Text]
renderConstructorBody aliases adapter =
    [ resolvedConstructor adapter <> renderArguments adapter.renderableAdapterFields <> " ="
    , "    frontendSurfaceResource"
    , "        @(AdapterFamilySurface " <> qualifyHaskellType aliases adapter.renderableAdapterHomeFamily <> ")"
    , "        @" <> qualifyHaskellType aliases adapter.renderableAdapterHomeDeclaration
    ]
        <> renderFieldsExpression aliases adapter.renderableAdapterFields

renderArguments :: [ResolvedAdapterField] -> Text
renderArguments fields =
    case map (haskellValueIdentifier . (.fieldName) . (.resolvedAdapterFieldIR)) fields of
        []    -> ""
        names -> " " <> Text.unwords names

renderFieldsExpression :: Map.Map Text Text -> [ResolvedAdapterField] -> [Text]
renderFieldsExpression _ [] = ["        NoSurfaceFields"]
renderFieldsExpression aliases (first : rest) =
    ["        ( " <> renderFieldBuilder aliases first]
        <> ["            :& " <> renderFieldBuilder aliases field | field <- rest]
        <> [ "            :& NoSurfaceFields"
           , "        )"
           ]

renderFieldBuilder :: Map.Map Text Text -> ResolvedAdapterField -> Text
renderFieldBuilder aliases field =
    helper <> " @" <> qualifyHaskellType aliases field.resolvedAdapterFieldMarker <> " " <> argument
  where
    helper = case field.resolvedAdapterFieldIR.fieldPresence of
        RequiredField         -> "surfaceField"
        OptionalFieldPresence -> "surfaceOptionalField"
        NullableFieldPresence -> "surfaceNullableField"
    argument = haskellValueIdentifier field.resolvedAdapterFieldIR.fieldName

renderMatcherSignature :: RenderableAdapter ResourceIR -> [Text]
renderMatcherSignature adapter =
    [ resolvedMatcher adapter <> " :: SurfaceResourceValue -> Maybe "
        <> renderFieldValueTuple (map (.resolvedAdapterFieldType) adapter.renderableAdapterFields)
    ]

renderMatcherBody ::
    Map.Map Text Text ->
    RenderableAdapter ResourceIR ->
    [Text]
renderMatcherBody aliases adapter =
    [ resolvedMatcher adapter <> " ="
    , "    matchFrontendSurfaceResource"
    , "        @(AdapterFamilySurface " <> qualifyHaskellType aliases adapter.renderableAdapterHomeFamily <> ")"
    , "        @" <> qualifyHaskellType aliases adapter.renderableAdapterHomeDeclaration
    ]

renderFieldValueTuple :: [HaskellSourceType] -> Text
renderFieldValueTuple = \case
    [] -> "()"
    field : rest -> "(" <> renderHaskellSourceType field <> ", " <> renderFieldValueTuple rest <> ")"

resolvedConstructor :: RenderableAdapter ResourceIR -> Text
resolvedConstructor adapter =
    case adapter.renderableAdapterGeneratedNames of
        constructorName : _ -> constructorName
        [] -> resourceConstructorName adapter.renderableAdapterHomeDeclaration.haskellTypeName

resolvedMatcher :: RenderableAdapter ResourceIR -> Text
resolvedMatcher adapter =
    case adapter.renderableAdapterGeneratedNames of
        _ : matcherName : _ -> matcherName
        _ -> "match" <> upperFirst (resolvedConstructor adapter)

resourceConstructorName :: Text -> Text
resourceConstructorName typeName =
    let words = wordsFromTypeName typeName
        base = lowerCamel words
     in if listToMaybe (reverse words) == Just "resource"
            then haskellValueIdentifier base
            else haskellValueIdentifier (base <> "Resource")

resourcesForSurface :: SurfaceIR -> [ResourceIR]
resourcesForSurface surface =
    surface.surfaceFragments
        |> concatMap (map (.dependencyResource) . optionResourceDependencies . (.fragmentOptions))
        |> List.nubBy
            (\left right ->
                left.resourceMarker == right.resourceMarker
                    && left.resourceFields == right.resourceFields
            )
