receivers:
  otlp:
    protocols:
      http:
        endpoint: 127.0.0.1:${env:BEPIS_RUNNER_OTLP_HTTP_PORT}
      grpc:
        endpoint: 127.0.0.1:${env:BEPIS_RUNNER_OTLP_GRPC_PORT}

processors:
  batch: {}

exporters:
  file:
    path: ${env:OTEL_FILE_EXPORTER_PATH}

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 127.0.0.1
                port: 0
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
