{-# LANGUAGE TypeApplications #-}

module Application.Helper.FrontendContract.Contracts
    ( TypeScriptDeclaration (..)
    , TypeScriptDeclarationOrigin (..)
    , frontendContractDeclarations
    , frontendContractsTypeScript
    , renderRegisteredFrontendContracts
    , renderTypeScriptDeclarations
    ) where

import Application.Helper.FrontendContract.IR (frontendContractIR)
import Application.Helper.FrontendContract.Registry (validateRegisteredFrontendContract)
import Application.Helper.FrontendContract.TypeScript (renderFrontendContractTypeScript)
import Control.Exception (Exception)
import qualified Control.Exception as Exception
import qualified Data.Text as Text
import IHP.Prelude

data TypeScriptDeclarationOrigin
    = HaskellSchemaGenerated
    deriving (Eq, Show)

data TypeScriptDeclaration = TypeScriptDeclaration
    { name   :: !Text
    , origin :: !TypeScriptDeclarationOrigin
    , source :: !Text
    } deriving (Eq, Show)

newtype FrontendContractGenerationException = FrontendContractGenerationException Text
    deriving (Show)

instance Exception FrontendContractGenerationException

frontendContractGlobalDeclaration :: TypeScriptDeclaration
frontendContractGlobalDeclaration = TypeScriptDeclaration
    { name = "FrontendContractGlobals"
    , origin = HaskellSchemaGenerated
    , source =
        case renderRegisteredFrontendContractSource of
            Right rendered -> rendered
            Left diagnostics -> Exception.throw (FrontendContractGenerationException diagnostics)
    }

renderRegisteredFrontendContractSource :: Either Text Text
renderRegisteredFrontendContractSource = do
    checked <- validateRegisteredFrontendContract
    renderFrontendContractTypeScript (frontendContractIR checked)

renderRegisteredFrontendContracts :: Either Text Text
renderRegisteredFrontendContracts =
    renderTypeScriptDeclarations
        . pure
        . TypeScriptDeclaration "FrontendContractGlobals" HaskellSchemaGenerated
        <$> renderRegisteredFrontendContractSource

frontendContractDeclarations :: [TypeScriptDeclaration]
frontendContractDeclarations =
    [ frontendContractGlobalDeclaration
    ]

frontendContractsTypeScript :: Text
frontendContractsTypeScript =
    renderTypeScriptDeclarations frontendContractDeclarations

renderTypeScriptDeclarations :: [TypeScriptDeclaration] -> Text
renderTypeScriptDeclarations declarations =
    Text.unlines $
        [ "// @generated by Application.Helper.FrontendContract.Contracts"
        , "// Do not edit by hand. Run: bash ./bin/in-env frontend-contracts"
        , ""
        ]
            <> fmap source declarations
