{-# LANGUAGE TypeApplications #-}

module Application.Helper.FrontendContract.Contracts
    ( TypeScriptDeclaration (..)
    , TypeScriptDeclarationOrigin (..)
    , frontendContractDeclarations
    , frontendContractsTypeScript
    , renderTypeScriptDeclarations
    ) where

import Application.Helper.FrontendContract.Registry (registeredFrontendContractIR)
import Application.Helper.FrontendContract.TypeScript (renderFrontendContractTypeScript)
import qualified Data.Text as Text
import IHP.Prelude

data TypeScriptDeclarationOrigin
    = HaskellSchemaGenerated
    deriving (Eq, Show)

data TypeScriptDeclaration = TypeScriptDeclaration
    { name   :: !Text
    , origin :: !TypeScriptDeclarationOrigin
    , source :: !Text
    } deriving (Eq, Show)

frontendContractGlobalDeclaration :: TypeScriptDeclaration
frontendContractGlobalDeclaration = TypeScriptDeclaration
    { name = "FrontendContractGlobals"
    , origin = HaskellSchemaGenerated
    , source = either error id (renderFrontendContractTypeScript registeredFrontendContractIR)
    }

frontendContractDeclarations :: [TypeScriptDeclaration]
frontendContractDeclarations =
    [ frontendContractGlobalDeclaration
    ]

frontendContractsTypeScript :: Text
frontendContractsTypeScript =
    renderTypeScriptDeclarations frontendContractDeclarations

renderTypeScriptDeclarations :: [TypeScriptDeclaration] -> Text
renderTypeScriptDeclarations declarations =
    Text.unlines $
        [ "// @generated by Application.Helper.FrontendContract.Contracts"
        , "// Do not edit by hand. Run: bash ./bin/in-env frontend-contracts"
        , ""
        ]
            <> fmap source declarations
