{-# LANGUAGE LambdaCase          #-}
{-# LANGUAGE NoImplicitPrelude   #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings   #-}

module Application.Helper.FrontendContract.TypeScript
    ( renderFrontendContractTypeScript
    ) where

import Application.Helper.FrontendContract.IR
import qualified Data.Char as Char
import qualified Data.List as List
import qualified Data.Text as Text
import IHP.Prelude

renderFrontendContractTypeScript :: FrontendContractIR -> Either Text Text
renderFrontendContractTypeScript contract = do
    checked <- case checkedFrontendContractIR contract of
        Right value -> Right value
        Left diagnostics -> Left (Text.intercalate "\n" (fmap (.diagnosticMessage) diagnostics))
    pure (Text.unlines (header <> renderDerivedSurfaceWireTypes checked.contractSurfaces <> concatMap (renderGlobal checked.contractSurfaces) checked.contractGlobals <> concatMap renderSurface checked.contractSurfaces <> renderFrontendSurfaceRuntime checked.contractSurfaces))

data WirePrimitiveTypeScript = WirePrimitiveTypeScript
    { primitiveWire      :: !WireIR
    , primitiveTypeName  :: !Text
    , primitiveTsRuntime :: !Text
    }

wirePrimitiveTypes :: [WirePrimitiveTypeScript]
wirePrimitiveTypes =
    [ WirePrimitiveTypeScript WireUuidIR "FrontendContractUuid" "string"
    , WirePrimitiveTypeScript WireDayIR "FrontendContractDay" "string"
    ]

wirePrimitiveTypeName :: WireIR -> Text
wirePrimitiveTypeName wire =
    case List.find ((== wire) . (.primitiveWire)) wirePrimitiveTypes of
        Just primitive -> primitive.primitiveTypeName
        Nothing        -> error ("No TypeScript primitive alias registered for " <> show wire)

wirePrimitiveRuntimeType :: WireIR -> Text
wirePrimitiveRuntimeType wire =
    case List.find ((== wire) . (.primitiveWire)) wirePrimitiveTypes of
        Just primitive -> primitive.primitiveTsRuntime
        Nothing        -> error ("No TypeScript primitive runtime type registered for " <> show wire)

renderWirePrimitiveAliases :: [Text]
renderWirePrimitiveAliases =
    [ "export type " <> primitive.primitiveTypeName <> " = " <> primitive.primitiveTsRuntime <> ";"
    | primitive <- wirePrimitiveTypes
    ]

header :: [Text]
header =
    [ "// Generated by Application.Helper.FrontendContract. Do not edit." ]
        <> renderWirePrimitiveAliases
        <> [ "export const FrontendSurfaceInteractionDom = { sourceRef: \"data-bepis-source-ref\", sourceKey: \"data-bepis-source-key\", dropzoneRef: \"data-bepis-dropzone-ref\", dropzoneKey: \"data-bepis-dropzone-key\", activationRef: \"data-bepis-activation-ref\" } as const;"
           , ""
           , "function isRecord(value: unknown): value is Record<string, unknown> {"
           , "    return typeof value === \"object\" && value !== null && !Array.isArray(value);"
           , "}"
           , ""
           ]

renderDerivedSurfaceWireTypes :: [SurfaceIR] -> [Text]
renderDerivedSurfaceWireTypes surfaces =
    concatMap renderSurfaceScopeUnion surfaces
        <> concatMap renderSurfaceFragmentKeyUnion surfaces
        <> renderTopLevelSurfaceScopeUnion surfaces
        <> renderTopLevelSurfaceFragmentKeyUnion surfaces
        <> renderTopLevelInteractionSurfaceVocabulary surfaces

renderSurfaceScopeUnion :: SurfaceIR -> [Text]
renderSurfaceScopeUnion surface =
    [ "export type " <> surfaceScopeUnionName surface <> " =" ]
        <> renderNamedUnion scopeTypes
        <> renderCodec (surfaceScopeUnionName surface) (orExpression ["is" <> scopeType <> "(value)" | scopeType <- scopeTypes])
    where
        scopeTypes = [surfaceScopeTypeName surface marker | SurfaceScopeIR marker _ _ <- surface.surfacePrimitives]

renderSurfaceFragmentKeyUnion :: SurfaceIR -> [Text]
renderSurfaceFragmentKeyUnion surface =
    [ "export type " <> surfaceFragmentKeyUnionName surface <> " =" ]
        <> renderFragmentKeyCases surface fragments
        <> renderCodec (surfaceFragmentKeyUnionName surface) (orExpression (fmap (fragmentKeyGuard surface) fragments))
    where
        fragments = [(marker, name, fields) | SurfaceFragmentIR marker name fields <- surface.surfacePrimitives]

renderTopLevelSurfaceScopeUnion :: [SurfaceIR] -> [Text]
renderTopLevelSurfaceScopeUnion surfaces =
    [ "export type SurfaceScope =" ]
        <> renderSurfaceScopeCases surfaces
        <> renderCodec "SurfaceScope" (orExpression (fmap surfaceScopeCaseGuard surfaces))

renderTopLevelSurfaceFragmentKeyUnion :: [SurfaceIR] -> [Text]
renderTopLevelSurfaceFragmentKeyUnion surfaces =
    [ "export type SurfaceFragmentKey =" ]
        <> renderTopLevelFragmentKeyCases surfaces
        <> renderCodec "SurfaceFragmentKey" (orExpression (fmap surfaceFragmentKeyCaseGuard surfaces))

renderTopLevelInteractionSurfaceVocabulary :: [SurfaceIR] -> [Text]
renderTopLevelInteractionSurfaceVocabulary surfaces =
    renderTopLevelStringUnion "FrontendSurfaceInteractionSurfaceName" (fmap (.surfaceName) interactionSurfaces)
        <> renderTopLevelStringUnion "FrontendSurfaceInteractionSessionKindName" (concatMap (.surfaceInteractionSessions) interactionSurfaces)
        <> renderTopLevelStringUnion "FrontendSurfaceInteractionDisposableLayerName" (concatMap (.surfaceInteractionLayers) interactionSurfaces)
        <> renderTopLevelStringUnion "FrontendSurfaceInteractionIntentName" [name | surface <- interactionSurfaces, SurfaceIntentIR _ name _ <- surface.surfacePrimitives]
        <> renderTopLevelStringUnion "FrontendSurfaceInteractionIntentFieldName" [field.fieldName | surface <- interactionSurfaces, SurfaceIntentIR _ _ fields <- surface.surfacePrimitives, field <- fields]
    where
        interactionSurfaces = filter (\surface -> surface.surfaceName /= "surface-lab" && surfaceHasInteractionSchema surface) surfaces

renderTopLevelStringUnion :: Text -> [Text] -> [Text]
renderTopLevelStringUnion typeName rawValues =
    [ "export type " <> typeName <> " = " <> renderStringUnion values <> ";"
    , "export function is" <> typeName <> "(value: unknown): value is " <> typeName <> " {"
    , "    return typeof value === \"string\" && [" <> Text.intercalate ", " (fmap quote values) <> "].includes(value);"
    , "}"
    , ""
    ]
    where
        values = List.nub rawValues

renderNamedUnion :: [Text] -> [Text]
renderNamedUnion names =
    case names of
        [] -> ["    never;", ""]
        _  -> zipWith render names [0 :: Int ..]
    where
        render name index = (if index == 0 then "    " else "  | ") <> name <> if index == length names - 1 then ";" else ""

renderSurfaceScopeCases :: [SurfaceIR] -> [Text]
renderSurfaceScopeCases surfaces =
    case surfaces of
        [] -> ["    never;", ""]
        _  -> zipWith render surfaces [0 :: Int ..]
    where
        render surface index =
            (if index == 0 then "    " else "  | ") <> "{ surface: " <> quote surface.surfaceName <> "; scope: " <> surfaceScopeUnionName surface <> " }" <> if index == length surfaces - 1 then ";" else ""

renderFragmentKeyCases :: SurfaceIR -> [(Text, Text, [FieldIR])] -> [Text]
renderFragmentKeyCases _ [] = ["    never;", ""]
renderFragmentKeyCases surface fragments = zipWith render fragments [0 :: Int ..]
    where
        render (marker, fragmentName, fields) index =
            (if index == 0 then "    " else "  | ") <> "{ kind: " <> quote fragmentName <> "; params: " <> fragmentParamsType surface marker fields <> " }" <> if index == length fragments - 1 then ";" else ""

renderTopLevelFragmentKeyCases :: [SurfaceIR] -> [Text]
renderTopLevelFragmentKeyCases [] = ["    never;", ""]
renderTopLevelFragmentKeyCases surfaces = zipWith render surfaces [0 :: Int ..]
    where
        render surface index =
            (if index == 0 then "    " else "  | ") <> "({ surface: " <> quote surface.surfaceName <> " } & " <> surfaceFragmentKeyUnionName surface <> ")" <> if index == length surfaces - 1 then ";" else ""

surfaceScopeCaseGuard :: SurfaceIR -> Text
surfaceScopeCaseGuard surface = "(isRecord(value) && value.surface === " <> quote surface.surfaceName <> " && is" <> surfaceScopeUnionName surface <> "(value.scope))"

surfaceFragmentKeyCaseGuard :: SurfaceIR -> Text
surfaceFragmentKeyCaseGuard surface = "(isRecord(value) && value.surface === " <> quote surface.surfaceName <> " && is" <> surfaceFragmentKeyUnionName surface <> "(value))"

fragmentKeyGuard :: SurfaceIR -> (Text, Text, [FieldIR]) -> Text
fragmentKeyGuard surface (marker, fragmentName, fields) =
    "(isRecord(value) && value.kind === " <> quote fragmentName <> " && (" <> paramsGuard <> "))"
    where
        paramsAccess = "value[\"params\"]"
        paramsGuard
            | null fields = paramsAccess <> " === null || " <> recordGuardExpressionWithAccess paramsAccess fields
            | otherwise = recordGuardExpressionWithAccess paramsAccess fields

recordGuardExpressionWithAccess :: Text -> [FieldIR] -> Text
recordGuardExpressionWithAccess access fields = Text.replace "value" access (recordGuardExpression fields)

fragmentParamsType :: SurfaceIR -> Text -> [FieldIR] -> Text
fragmentParamsType surface marker fields
    | null fields = surfaceFragmentParamsTypeName surface marker <> " | null"
    | otherwise = surfaceFragmentParamsTypeName surface marker

orExpression :: [Text] -> Text
orExpression expressions =
    case expressions of
        [] -> "false"
        _  -> "(" <> Text.intercalate " || " expressions <> ")"

surfaceScopeUnionName :: SurfaceIR -> Text
surfaceScopeUnionName surface = surfaceTypePrefix surface <> "SurfaceScope"

surfaceFragmentKeyUnionName :: SurfaceIR -> Text
surfaceFragmentKeyUnionName surface = surfaceTypePrefix surface <> "SurfaceFragmentKey"

surfaceScopeTypeName :: SurfaceIR -> Text -> Text
surfaceScopeTypeName surface marker = surfaceTypePrefix surface <> typeNameFromMarker marker <> "Scope"

surfaceFragmentParamsTypeName :: SurfaceIR -> Text -> Text
surfaceFragmentParamsTypeName surface marker = surfaceTypePrefix surface <> typeNameFromMarker marker <> "FragmentParams"

renderGlobal :: [SurfaceIR] -> GlobalIR -> [Text]
renderGlobal surfaces global = concatMap renderGlobalPrimitive global.globalPrimitives <> renderGlobalConvenienceGroups surfaces global

renderGlobalPrimitive :: GlobalPrimitiveIR -> [Text]
renderGlobalPrimitive = \case
    GlobalSchemaIR schema -> renderSchema schema
    GlobalEventIR marker eventName fields -> renderRecordAlias (typeNameFromMarker marker <> "EventDetail") fields <> ["export const " <> constName marker <> "Event = " <> quote eventName <> " as const;", ""]
    GlobalDomIdIR marker domId -> ["export const " <> constName marker <> "DomId = " <> quote domId <> " as const;", ""]
    GlobalDomAttrIR marker attr -> ["export const " <> constName marker <> "DomAttr = " <> quote attr <> " as const;", ""]
    GlobalDomValueIR marker value -> ["export const " <> constName marker <> "DomValue = " <> quote value <> " as const;", ""]
    GlobalFieldNameIR marker name -> ["export const " <> constName marker <> "FieldName = " <> quote name <> " as const;", ""]
    GlobalDomTokenIR marker token -> ["export const " <> constName marker <> "DomToken = " <> quote token <> " as const;", ""]
    GlobalAppShellActionIR action -> renderAppShellActionAlias action <> ["export const " <> constName action.appShellActionMarker <> "AppShellActionManifest = " <> renderAppShellActionManifest action <> " as const;", ""]

renderAppShellActionAlias :: AppShellActionIR -> [Text]
renderAppShellActionAlias action =
    renderRecordAlias (typeNameFromMarker action.appShellActionMarker <> "AppShellActionFields") action.appShellActionFields

renderAppShellActionManifest :: AppShellActionIR -> Text
renderAppShellActionManifest action = objectLiteral
    [ ("name", quote action.appShellActionName)
    , ("fields", arrayLiteral (fmap (quote . (.fieldName)) action.appShellActionFields))
    , ("htmx", renderSurfaceActionHtmxOptions action.appShellActionOptions)
    ]

renderGlobalConvenienceGroups :: [SurfaceIR] -> GlobalIR -> [Text]
renderGlobalConvenienceGroups surfaces global
    | global.globalName == "interaction" = renderInteractionDomGroup global.globalPrimitives <> renderInteractionStaticSchemas surfaces
    | otherwise = []

renderInteractionStaticSchemas :: [SurfaceIR] -> [Text]
renderInteractionStaticSchemas surfaces =
    renderWireAlias "InteractionStaticSchemaRegistry" (WireMapIR (WireRefIR "FrontendSurfaceInteractionSurfaceName") (WireRefIR "InteractionStaticSchema"))
        <> [ "export const InteractionStaticSchemas: InteractionStaticSchemaRegistry = " <> objectLiteral surfaceEntries <> ";"
           , ""
           ]
    where
        interactionSurfaces = filter (\surface -> surface.surfaceName /= "surface-lab" && surfaceHasInteractionSchema surface) surfaces
        surfaceEntries = [(constName surface.surfaceName, renderStaticSchema surface) | surface <- interactionSurfaces]

surfaceHasInteractionSchema :: SurfaceIR -> Bool
surfaceHasInteractionSchema surface =
    not (null surface.surfaceInteractionLayers)
        || not (null surface.surfaceInteractionSessions)
        || not (null (surfaceIntentPrimitives surface))
        || not (null surface.surfaceInteractionPolicies)

renderStaticSchema :: SurfaceIR -> Text
renderStaticSchema surface = objectLiteral
    [ ("serverLayers", arrayLiteral [])
    , ("disposableLayers", arrayLiteral (fmap renderDisposableLayer surface.surfaceInteractionLayers))
    , ("sessionKinds", arrayLiteral (fmap (renderSessionKind surface) surface.surfaceInteractionSessions))
    , ("intents", arrayLiteral (fmap renderStaticIntent (surfaceIntentPrimitives surface)))
    , ("conflictPolicies", arrayLiteral (fmap renderConflictPolicy surface.surfaceInteractionPolicies))
    ]

renderDisposableLayer :: Text -> Text
renderDisposableLayer name = objectLiteral [("name", quote name), ("domIdSuffix", quote name)]

renderSessionKind :: SurfaceIR -> Text -> Text
renderSessionKind surface session = objectLiteral
    [ ("kind", quote session)
    , ("description", quote (surfaceSessionDescription surface.surfaceName session))
    , ("effects", renderSessionEffects surface.surfaceInteractionEffects)
    ]

surfaceSessionDescription :: Text -> Text -> Text
surfaceSessionDescription "roster" "drag" = "Roster drag/drop prototype"
surfaceSessionDescription surfaceName sessionName = surfaceName <> " " <> sessionName <> " interaction session"

renderSessionEffects :: [(Text, [Text])] -> Text
renderSessionEffects effects = objectLiteral
    [ ("global", arrayLiteral (mapMaybe renderGlobalEffect effects))
    , ("contextual", arrayLiteral (mapMaybe renderContextualEffect effects))
    ]

renderGlobalEffect :: (Text, [Text]) -> Maybe Text
renderGlobalEffect ("clone-shadow", layers) = Just $ renderCloneShadowEffect "bepis-pointer-clone-shadow" layers
renderGlobalEffect ("clone-shadow-copy", layers) = Just $ renderCloneShadowEffect "bepis-pointer-clone-shadow bepis-pointer-clone-shadow-copy" layers
renderGlobalEffect _ = Nothing

renderCloneShadowEffect :: Text -> [Text] -> Text
renderCloneShadowEffect className layers = objectLiteral
    [ ("className", quote className)
    , ("kind", quote "clone-shadow")
    , ("layer", quote (fromMaybe "drag-preview" (listToMaybe layers)))
    , ("preserveGrabOffset", "true")
    , ("source", quote "pointer-marker")
    ]

renderContextualEffect :: (Text, [Text]) -> Maybe Text
renderContextualEffect ("dropzone-highlight", _) = Just $ objectLiteral
    [ ("className", quote "bepis-dropzone-highlight")
    , ("kind", quote "dropzone-highlight")
    ]
renderContextualEffect _ = Nothing

surfaceIntentPrimitives :: SurfaceIR -> [(Text, [FieldIR])]
surfaceIntentPrimitives surface = [(name, fields) | SurfaceIntentIR _ name fields <- surface.surfacePrimitives]

renderStaticIntent :: (Text, [FieldIR]) -> Text
renderStaticIntent (name, fields) = objectLiteral
    [ ("name", quote name)
    , ("fields", arrayLiteral (fmap renderIntentField fields))
    ]

renderIntentField :: FieldIR -> Text
renderIntentField field = objectLiteral
    [ ("name", quote field.fieldName)
    , ("presence", quote (fieldPresenceValue field.fieldPresence))
    , ("defaultValue", "null")
    ]

fieldPresenceValue :: FieldPresence -> Text
fieldPresenceValue RequiredField         = "required"
fieldPresenceValue OptionalFieldPresence = "optional"
fieldPresenceValue NullableFieldPresence = "optional"

renderConflictPolicy :: SurfaceInteractionPolicyIR -> Text
renderConflictPolicy policy = objectLiteral $ baseFields <> timeoutField
    where
        baseFields =
            [ ("session", maybe (objectLiteral [("kind", quote "any")]) (\session -> objectLiteral [("kind", quote "session"), ("session", quote session)]) policy.interactionPolicySession)
            , ("fragment", objectLiteral [("kind", quote "any")])
            , ("resolution", quote policy.interactionPolicyResolution)
            ]
        timeoutField = if policy.interactionPolicyResolution == "defer" then [("timeoutMs", "5000")] else []

objectLiteral :: [(Text, Text)] -> Text
objectLiteral fields = "{" <> Text.intercalate "," [quote key <> ":" <> value | (key, value) <- fields] <> "}"

arrayLiteral :: [Text] -> Text
arrayLiteral values = "[" <> Text.intercalate "," values <> "]"

renderInteractionDomGroup :: [GlobalPrimitiveIR] -> [Text]
renderInteractionDomGroup primitives =
    [ "export type InteractionDomAttributes = {"
    ]
        <> fmap renderAttrType attrs
        <> [ "};"
           , "export type InteractionDomValues = {"
           ]
        <> fmap renderValueType values
        <> [ "};"
           , "export type InteractionPointerFields = {"
           ]
        <> fmap renderFieldType fields
        <> [ "};"
           , "export type InteractionDom = { attributes: InteractionDomAttributes; values: InteractionDomValues; pointerFields: InteractionPointerFields };"
           , "export const InteractionDom: InteractionDom = {"
           , "    attributes: { " <> Text.intercalate ", " (fmap renderAttrValue attrs) <> " },"
           , "    values: { " <> Text.intercalate ", " (fmap renderDomValue values) <> " },"
           , "    pointerFields: { " <> Text.intercalate ", " (fmap renderFieldValue fields) <> " },"
           , "};"
           , ""
           ]
    where
        attrs = [(marker, value) | GlobalDomAttrIR marker value <- primitives]
        values = [(marker, value) | GlobalDomValueIR marker value <- primitives]
        fields = [(marker, value) | GlobalFieldNameIR marker value <- primitives]
        renderAttrType (marker, _) = "    " <> constName marker <> ": typeof " <> constName marker <> "DomAttr;"
        renderValueType (marker, _) = "    " <> constName marker <> ": typeof " <> constName marker <> "DomValue;"
        renderFieldType (marker, _) = "    " <> constName marker <> ": typeof " <> constName marker <> "FieldName;"
        renderAttrValue (marker, _) = constName marker <> ": " <> constName marker <> "DomAttr"
        renderDomValue (marker, _) = constName marker <> ": " <> constName marker <> "DomValue"
        renderFieldValue (marker, _) = constName marker <> ": " <> constName marker <> "FieldName"

renderSurface :: SurfaceIR -> [Text]
renderSurface surface = concatMap (renderSurfacePrimitive surface) surface.surfacePrimitives

renderFrontendSurfaceRuntime :: [SurfaceIR] -> [Text]
renderFrontendSurfaceRuntime surfaces =
    renderFrontendSurfaceBrandAliases surfaces
        <> concatMap renderFrontendSurfaceAliases surfaces
        <> renderFrontendSurfaceLiveTransport surfaces
        <> renderFrontendSurfaceMountConfigTypes
        <> renderFrontendSurfaceRegistry surfaces

renderFrontendSurfaceBrandAliases :: [SurfaceIR] -> [Text]
renderFrontendSurfaceBrandAliases surfaces =
    [ "export type " <> alias <> " = " <> wirePrimitiveTypeName WireUuidIR <> ";"
    | alias <- List.nub (concatMap surfaceUuidAliases surfaces)
    ] <> ["" | not (null (concatMap surfaceUuidAliases surfaces))]

surfaceUuidAliases :: SurfaceIR -> [Text]
surfaceUuidAliases surface =
    [ typeNameFromMarker field.fieldMarker
    | primitive <- surface.surfacePrimitives
    , field <- surfacePrimitiveFields primitive
    , isUuidWire field.fieldWire
    ]

surfacePrimitiveFields :: SurfacePrimitiveIR -> [FieldIR]
surfacePrimitiveFields = \case
    SurfaceSchemaIR _ -> []
    SurfaceScopeIR _ _ fields -> fields
    SurfaceFragmentIR _ _ fields -> fields
    SurfaceActionIR _ _ fields _ -> fields
    SurfaceIntentIR _ _ fields -> fields
    SurfaceMountStateIR _ _ fields -> fields
    SurfaceDtoIR _ _ fields -> fields

isUuidWire :: WireIR -> Bool
isUuidWire = \case
    WireUuidIR -> True
    WireOptionalIR inner -> isUuidWire inner
    WireNullableIR inner -> isUuidWire inner
    WireListIR inner -> isUuidWire inner
    _ -> False

renderFrontendSurfaceAliases :: SurfaceIR -> [Text]
renderFrontendSurfaceAliases surface =
    [ "export type " <> prefix <> "SurfaceName = " <> quote surface.surfaceName <> ";" ]
        <> ["export type " <> prefix <> "FragmentKey = " <> surfaceFragmentKeyUnionName surface <> ";" | hasFragments]
        <> concatMap renderMountStateAlias surface.surfacePrimitives
        <> concatMap renderActionAlias surface.surfacePrimitives
        <> concatMap renderIntentAlias surface.surfacePrimitives
        <> renderVocabulary (prefix <> "SessionName") surface.surfaceInteractionSessions
        <> renderVocabulary (prefix <> "SourceRef") [ref.interactionSourceRefName | ref <- surface.surfaceSourceRefs]
        <> renderVocabulary (prefix <> "DropzoneRef") [ref | (ref, _, _) <- surface.surfaceDropzoneRefs]
        <> renderVocabulary (prefix <> "ActivationRef") [ref | (ref, _, _, _) <- surface.surfaceActivationRefs]
        <> renderVocabulary (prefix <> "DisposableLayerName") surface.surfaceInteractionLayers
        <> renderVocabulary (prefix <> "DomToken") surface.surfaceDomTokens
        <> renderVocabulary (prefix <> "OverlayLane") surface.surfaceOverlayLanes
        <> [ "export const " <> constName surface.surfaceName <> "SurfaceManifest = " <> renderFrontendSurfaceManifest surface <> " as const;"
           , ""
           ]
    where
        prefix = protocolTypeName surface.surfaceName
        hasFragments = any isFragment surface.surfacePrimitives
        isFragment SurfaceFragmentIR {} = True
        isFragment _                    = False
        renderMountStateAlias = \case
            SurfaceMountStateIR marker name _ -> ["export type " <> mountStateAliasName name <> " = " <> surfaceTypePrefix surface <> typeNameFromMarker marker <> "MountState;"]
            _ -> []
        renderActionAlias = \case
            SurfaceActionIR marker name _ _ -> ["export type " <> typeNameFromMarker name <> "ActionFields = " <> surfaceTypePrefix surface <> typeNameFromMarker marker <> "ActionFields;"]
            _ -> []
        renderIntentAlias = \case
            SurfaceIntentIR marker name _ -> ["export type " <> typeNameFromMarker name <> "IntentFields = " <> surfaceTypePrefix surface <> typeNameFromMarker marker <> "IntentFields;"]
            _ -> []
        mountStateAliasName name =
            let base = typeNameFromMarker name
             in if "MountState" `Text.isSuffixOf` base then base else base <> "MountState"

renderVocabulary :: Text -> [Text] -> [Text]
renderVocabulary typeName values =
    [ "export type " <> typeName <> " = " <> renderStringUnion values <> ";" | not (null values) ]

renderStringUnion :: [Text] -> Text
renderStringUnion values =
    case values of
        [] -> "never"
        _  -> Text.intercalate " | " (fmap quote values)

renderFrontendSurfaceManifest :: SurfaceIR -> Text
renderFrontendSurfaceManifest surface =
    objectLiteral
        [ ("surface", quote surface.surfaceName)
        , ("scopes", arrayLiteral (fmap quote [name | SurfaceScopeIR _ name _ <- surface.surfacePrimitives]))
        , ("fragments", arrayLiteral (fmap quote [name | SurfaceFragmentIR _ name _ <- surface.surfacePrimitives]))
        , ("liveFragments", arrayLiteral (fmap quote surface.surfaceLiveFragments))
        , ("htmxActions", arrayLiteral (fmap renderSurfaceActionManifest [action | action@SurfaceActionIR {} <- surface.surfacePrimitives]))
        , ("intents", arrayLiteral (fmap quote [name | SurfaceIntentIR _ name _ <- surface.surfacePrimitives]))
        , ("sessions", arrayLiteral (fmap quote surface.surfaceInteractionSessions))
        , ("interaction", renderFrontendSurfaceInteractionManifest surface)
        , ("layers", arrayLiteral (fmap quote surface.surfaceInteractionLayers))
        , ("domTokens", arrayLiteral (fmap quote surface.surfaceDomTokens))
        , ("overlayLanes", arrayLiteral (fmap quote surface.surfaceOverlayLanes))
        , ("containedSurfaces", renderContainedSurfaceMap surface)
        ]

renderSurfaceActionManifest :: SurfacePrimitiveIR -> Text
renderSurfaceActionManifest = \case
    SurfaceActionIR _ name fields options -> objectLiteral
        [ ("name", quote name)
        , ("fields", arrayLiteral (fmap (quote . (.fieldName)) fields))
        , ("htmx", renderSurfaceActionHtmxOptions options)
        ]
    _ -> objectLiteral []

renderSurfaceActionHtmxOptions :: [HtmxActionOptionIR] -> Text
renderSurfaceActionHtmxOptions options = objectLiteral
    [ ("method", maybe "null" quote (listToMaybe [value | HtmxActionMethodIR value <- options]))
    , ("trigger", maybe "null" quote (listToMaybe [value | HtmxActionTriggerIR value <- options]))
    , ("include", maybe "null" quote (listToMaybe [value | HtmxActionIncludeIR value <- options]))
    , ("sync", maybe "null" quote (listToMaybe [value | HtmxActionSyncIR value <- options]))
    , ("indicator", maybe "null" quote (listToMaybe [value | HtmxActionIndicatorIR value <- options]))
    , ("confirm", maybe "null" quote (listToMaybe [value | HtmxActionConfirmIR value <- options]))
    , ("select", maybe "null" quote (listToMaybe [value | HtmxActionSelectIR value <- options]))
    , ("target", maybe "null" quote (listToMaybe [value | HtmxActionTargetIR value <- options]))
    , ("swap", maybe "null" quote (listToMaybe [value | HtmxActionSwapIR value <- options]))
    , ("pushUrl", maybe "null" boolLiteral (listToMaybe [value | HtmxActionPushUrlIR value <- options]))
    , ("custom", arrayLiteral [objectLiteral [("name", quote marker), ("reason", quote reason)] | HtmxActionCustomHtmxIR marker reason <- options])
    ]

boolLiteral :: Bool -> Text
boolLiteral True  = "true"
boolLiteral False = "false"

renderFrontendSurfaceInteractionManifest :: SurfaceIR -> Text
renderFrontendSurfaceInteractionManifest surface = objectLiteral
    [ ("sourceRefs", arrayLiteral (fmap renderSourceRef surface.surfaceSourceRefs))
    , ("dropzoneRefs", arrayLiteral (fmap renderDropzoneRef surface.surfaceDropzoneRefs))
    , ("activationRefs", arrayLiteral (fmap renderActivationRef surface.surfaceActivationRefs))
    ]

renderSourceRef :: InteractionSourceRefIR -> Text
renderSourceRef ref = objectLiteral
    [ ("ref", quote ref.interactionSourceRefName)
    , ("session", quote ref.interactionSourceRefSession)
    , ("intent", quote ref.interactionSourceRefIntent)
    , ("sourceField", quote ref.interactionSourceRefSourceField)
    , ("modifierVariants", arrayLiteral (fmap renderModifierVariant ref.interactionSourceRefVariants))
    ]

renderModifierVariant :: InteractionModifierVariantIR -> Text
renderModifierVariant variant = objectLiteral
    [ ("semantic", quote variant.interactionModifierSemantic)
    , ("intent", quote variant.interactionModifierIntent)
    , ("effects", renderSessionEffects variant.interactionModifierEffects)
    ]

renderDropzoneRef :: (Text, Text, Text) -> Text
renderDropzoneRef (ref, session, targetField) = objectLiteral [("ref", quote ref), ("session", quote session), ("targetField", quote targetField)]

renderActivationRef :: (Text, Text, Maybe Text, Text) -> Text
renderActivationRef (ref, intent, valueField, trigger) = objectLiteral [("ref", quote ref), ("intent", quote intent), ("valueField", maybe "null" quote valueField), ("trigger", quote trigger)]

renderContainedSurfaceMap :: SurfaceIR -> Text
renderContainedSurfaceMap surface =
    objectLiteral [(fragment, arrayLiteral (fmap quote children)) | (fragment, children) <- surface.surfaceContainedSurfaces]

renderFrontendSurfaceLiveTransport :: [SurfaceIR] -> [Text]
renderFrontendSurfaceLiveTransport surfaces =
    -- FrontendSurface* live types model server-rendered mount metadata.
    -- They intentionally bridge from HTML data attributes into the canonical
    -- SurfaceScope/SurfaceFragmentKey/SurfaceWireFragment websocket contract
    -- types above; they are runtime convenience views, not a second contract
    -- authority.
    [ "// FrontendSurface* live types are server-rendered mount metadata adapters."
    , "// Canonical websocket wire contracts remain SurfaceScope, SurfaceFragmentKey, and SurfaceWireFragment."
    , "export type FrontendSurfaceScope ="
    ]
        <> renderFrontendSurfaceScopeCases liveSurfaces
        <> [ "export type FrontendSurfaceLiveFragment =" ]
        <> renderFrontendSurfaceLiveFragmentCases liveSurfaces
        <> [ "export function isFrontendSurfaceScope(value: unknown): value is FrontendSurfaceScope {"
           , "    if (!isRecord(value)) return false;"
           , "    if (!isFrontendSurfaceName(value.surface)) return false;"
           , "    return isRecord(value.scope);"
           , "}"
           , "export function parseFrontendSurfaceScope(value: unknown): FrontendSurfaceScope {"
           , "    if (isFrontendSurfaceScope(value)) return value;"
           , "    throw new Error(\"Invalid FrontendSurfaceScope\");"
           , "}"
           , "export function isFrontendSurfaceLiveFragment(value: unknown): value is FrontendSurfaceLiveFragment {"
           , "    if (!isRecord(value)) return false;"
           , "    if (!isFrontendSurfaceName(value.surface)) return false;"
           , "    if (!isRecord(value.fragment)) return false;"
           , "    return typeof value.fragment.kind === \"string\" && __surfaceHasFragment(value.surface, value.fragment.kind);"
           , "}"
           , "export function parseFrontendSurfaceLiveFragment(value: unknown): FrontendSurfaceLiveFragment {"
           , "    if (isFrontendSurfaceLiveFragment(value)) return value;"
           , "    throw new Error(\"Invalid FrontendSurfaceLiveFragment\");"
           , "}"
           , ""
           ]
    where
        liveSurfaces = filter (not . null . (.surfaceLiveFragments)) surfaces

renderFrontendSurfaceScopeCases :: [SurfaceIR] -> [Text]
renderFrontendSurfaceScopeCases [] = ["    never;"]
renderFrontendSurfaceScopeCases surfaces = zipWith render surfaces [0 :: Int ..]
    where
        render surface index =
            case [surfaceScopeTypeName surface marker | SurfaceScopeIR marker _ _ <- surface.surfacePrimitives] of
                scopeType : _ -> (if index == 0 then "    " else "  | ") <> "{ surface: " <> quote surface.surfaceName <> "; scope: " <> scopeType <> " }" <> if index == length surfaces - 1 then ";" else ""
                [] -> ""

renderFrontendSurfaceLiveFragmentCases :: [SurfaceIR] -> [Text]
renderFrontendSurfaceLiveFragmentCases [] = ["    never;"]
renderFrontendSurfaceLiveFragmentCases surfaces = zipWith render surfaces [0 :: Int ..]
    where
        render surface index = (if index == 0 then "    " else "  | ") <> "{ surface: " <> quote surface.surfaceName <> "; fragment: " <> surfaceFragmentKeyUnionName surface <> " }" <> if index == length surfaces - 1 then ";" else ""

renderFrontendSurfaceSupportSchemas :: [Text]
renderFrontendSurfaceSupportSchemas =
    concatMap renderSchema generatedSchemas
        <> concatMap renderSchemaTypeOnly adapterTypeOnlySchemas
    where
        generatedSchemas =
            [ RecordIR "HtmxCustomHtmxAttribute" "HtmxCustomHtmxAttribute"
                [ required "Name" "name" WireTextIR
                , required "Reason" "reason" WireTextIR
                ]
            , RecordIR "HtmxActionOptions" "HtmxActionOptions"
                [ nullable "Method" "method" (WireRefIR "HtmxActionMethod")
                , nullable "Trigger" "trigger" WireTextIR
                , nullable "Include" "include" WireTextIR
                , nullable "Sync" "sync" WireTextIR
                , nullable "Indicator" "indicator" WireTextIR
                , nullable "Confirm" "confirm" WireTextIR
                , nullable "Select" "select" WireTextIR
                , nullable "Target" "target" WireTextIR
                , nullable "Swap" "swap" (WireRefIR "HtmxActionSwap")
                , nullable "PushUrl" "pushUrl" WireBoolIR
                , required "Custom" "custom" (WireListIR (WireRefIR "HtmxCustomHtmxAttribute"))
                ]
            , RecordIR "FrontendSurfaceActionManifest" "FrontendSurfaceActionManifest"
                [ required "Name" "name" WireTextIR
                , required "Fields" "fields" (WireListIR WireTextIR)
                , required "Htmx" "htmx" (WireRefIR "HtmxActionOptions")
                ]
            , RecordIR "AppShellActionManifest" "AppShellActionManifest"
                [ required "Name" "name" WireTextIR
                , required "Fields" "fields" (WireListIR WireTextIR)
                , required "Htmx" "htmx" (WireRefIR "HtmxActionOptions")
                ]
            , TaggedUnionIR "FrontendSurfaceSurfaceFragmentProtection" "FrontendSurfaceSurfaceFragmentProtection" "kind"
                [ UnionCaseIR "None" "none" []
                , UnionCaseIR "FocusedField" "focused-field"
                    [ required "ActiveSelector" "activeSelector" WireTextIR
                    , required "FieldKeyAttr" "fieldKeyAttr" WireTextIR
                    , required "FieldNameFallback" "fieldNameFallback" WireBoolIR
                    , nullable "ContainerSelector" "containerSelector" WireTextIR
                    ]
                ]
            , RecordIR "FrontendSurfaceLiveWireFragment" "FrontendSurfaceLiveWireFragment"
                [ required "Fragment" "fragment" (WireRefIR "FrontendSurfaceLiveFragment")
                , required "TargetId" "targetId" WireTextIR
                , required "Url" "url" WireTextIR
                , required "DeferUntilBlur" "deferUntilBlur" WireBoolIR
                , required "ProtectionPolicy" "protectionPolicy" (WireRefIR "FrontendSurfaceSurfaceFragmentProtection")
                ]
            , RecordIR "FrontendSurfaceLiveSubscription" "FrontendSurfaceLiveSubscription"
                [ required "Scope" "scope" (WireRefIR "FrontendSurfaceScope")
                , required "ScopeKey" "scopeKey" WireTextIR
                , required "ResyncFragments" "resyncFragments" (WireListIR (WireRefIR "FrontendSurfaceLiveWireFragment"))
                ]
            ]
        adapterTypeOnlySchemas =
            [ RecordIR "FrontendSurfaceMountedFragmentKeyConfig" "FrontendSurfaceMountedFragmentKeyConfig"
                [ required "Kind" "kind" WireTextIR
                , required "Params" "params" WireUnknownIR
                ]
            , RecordIR "FrontendSurfaceMountedFragmentConfig" "FrontendSurfaceMountedFragmentConfig"
                [ required "Key" "key" (WireRefIR "FrontendSurfaceMountedFragmentKeyConfig")
                , required "TargetId" "targetId" WireTextIR
                , required "Url" "url" WireTextIR
                , nullable "Protection" "protection" WireUnknownIR
                , nullable "LoadPolicy" "loadPolicy" WireTextIR
                ]
            , RecordIR "FrontendSurfaceMountConfig" "FrontendSurfaceMountConfig"
                [ required "Surface" "surface" (WireRefIR "FrontendSurfaceName")
                , required "ScopeKey" "scopeKey" WireTextIR
                , required "MountKey" "mountKey" WireTextIR
                , required "MountState" "mountState" WireUnknownIR
                , required "Fragments" "fragments" (WireListIR (WireRefIR "FrontendSurfaceMountedFragmentConfig"))
                , nullable "Subscription" "subscription" (WireRefIR "FrontendSurfaceLiveSubscription")
                ]
            ]
        required marker name wire = FieldIR marker name wire RequiredField
        nullable marker name wire = FieldIR marker name wire NullableFieldPresence

renderSchemaTypeOnly :: SchemaIR -> [Text]
renderSchemaTypeOnly = \case
    RecordIR _ name fields -> ["export type " <> name <> " = " <> recordType fields <> ";"]
    EnumIR _ name values -> ["export type " <> name <> " ="] <> renderUnionValues values
    LiteralEnumIR _ name values -> ["export type " <> name <> " ="] <> renderUnionValues (fmap snd values)
    TaggedUnionIR _ name discriminator cases -> ["export type " <> name <> " ="] <> renderUnionCases discriminator cases

renderFrontendSurfaceMountConfigTypes :: [Text]
renderFrontendSurfaceMountConfigTypes =
    renderFrontendSurfaceSupportSchemas
        <> [ "// FrontendSurfaceMountConfig is the HTML data attribute shape emitted by Haskell views."
           , "// Runtime parsing/normalization lives in frontend/ts/live-updates/frontend-surface.ts."
           , "function __surfaceHasFragment(surface: FrontendSurfaceName, fragment: string): boolean {"
    , "    return (FrontendSurfaceRegistry[surface].fragments as readonly string[]).includes(fragment);"
    , "}"
    , ""
    ]

renderFrontendSurfaceRegistry :: [SurfaceIR] -> [Text]
renderFrontendSurfaceRegistry surfaces =
    [ "export type FrontendSurfaceName = " <> renderStringUnion (fmap (.surfaceName) surfaces) <> ";"
    , "export const FrontendSurfaceRegistry = {"
    ]
        <> fmap (\surface -> "    " <> propertyName surface.surfaceName <> ": " <> constName surface.surfaceName <> "SurfaceManifest,") surfaces
        <> [ "} as const;"
           , "export function isFrontendSurfaceName(value: unknown): value is FrontendSurfaceName {"
           , "    return typeof value === \"string\" && Object.prototype.hasOwnProperty.call(FrontendSurfaceRegistry, value);"
           , "}"
           , "export function parseFrontendSurfaceName(value: unknown): FrontendSurfaceName {"
           , "    if (isFrontendSurfaceName(value)) return value;"
           , "    throw new Error(\"Invalid FrontendSurfaceName\");"
           , "}"
           , "export type FrontendSurfaceContainmentEdge = { parentSurface: FrontendSurfaceName; parentFragment: string; childSurface: FrontendSurfaceName };"
           , "export const FrontendSurfaceContainmentTopology = ["
           ]
        <> concatMap renderContainmentEdges surfaces
        <> [ "] as const;"
           , "export function isFrontendSurfaceContainmentEdge(value: unknown): value is FrontendSurfaceContainmentEdge {"
           , "    if (!isRecord(value)) return false;"
           , "    return isFrontendSurfaceName(value.parentSurface) && typeof value.parentFragment === \"string\" && isFrontendSurfaceName(value.childSurface);"
           , "}"
           , "export function isFrontendSurfaceSourceRef(surface: FrontendSurfaceName, value: unknown): value is string {"
           , "    return typeof value === \"string\" && (FrontendSurfaceRegistry[surface].interaction.sourceRefs as readonly { readonly ref: string }[]).some((entry) => entry.ref === value);"
           , "}"
           , "export function isFrontendSurfaceDropzoneRef(surface: FrontendSurfaceName, value: unknown): value is string {"
           , "    return typeof value === \"string\" && (FrontendSurfaceRegistry[surface].interaction.dropzoneRefs as readonly { readonly ref: string }[]).some((entry) => entry.ref === value);"
           , "}"
           , "export function isFrontendSurfaceActivationRef(surface: FrontendSurfaceName, value: unknown): value is string {"
           , "    return typeof value === \"string\" && (FrontendSurfaceRegistry[surface].interaction.activationRefs as readonly { readonly ref: string }[]).some((entry) => entry.ref === value);"
           , "}"
           , ""
           ]

renderContainmentEdges :: SurfaceIR -> [Text]
renderContainmentEdges surface =
    [ "    { parentSurface: " <> quote surface.surfaceName <> ", parentFragment: " <> quote fragment <> ", childSurface: " <> quote child <> " },"
    | (fragment, children) <- surface.surfaceContainedSurfaces
    , child <- children
    ]

renderSurfacePrimitive :: SurfaceIR -> SurfacePrimitiveIR -> [Text]
renderSurfacePrimitive surface = \case
    SurfaceSchemaIR schema -> renderSchema schema
    SurfaceScopeIR marker _ fields -> renderRecordAlias (surfaceTypePrefix surface <> typeNameFromMarker marker <> "Scope") fields
    SurfaceFragmentIR marker _ fields -> renderRecordAlias (surfaceTypePrefix surface <> typeNameFromMarker marker <> "FragmentParams") fields
    SurfaceActionIR marker _ fields _ -> renderRecordAlias (surfaceTypePrefix surface <> typeNameFromMarker marker <> "ActionFields") fields
    SurfaceIntentIR marker _ fields -> renderRecordAlias (surfaceTypePrefix surface <> typeNameFromMarker marker <> "IntentFields") fields
    SurfaceMountStateIR marker _ fields -> renderRecordAlias (surfaceTypePrefix surface <> typeNameFromMarker marker <> "MountState") fields
    SurfaceDtoIR marker _ fields -> renderRecordAlias (typeNameFromMarker marker) fields

renderSchema :: SchemaIR -> [Text]
renderSchema = \case
    RecordIR _ name fields -> renderRecordAlias name fields
    EnumIR _ name values ->
        [ "export type " <> name <> " =" ]
            <> renderUnionValues values
            <> renderCodec name (isEnumExpression values)
    LiteralEnumIR _ name values ->
        let literalValues = fmap snd values
         in [ "export type " <> name <> " =" ]
            <> renderUnionValues literalValues
            <> renderCodec name (isEnumExpression literalValues)
    TaggedUnionIR _ name discriminator cases ->
        [ "export type " <> name <> " =" ]
            <> renderUnionCases discriminator cases
            <> renderCodec name ("(" <> Text.intercalate " || " (fmap (caseGuard discriminator) cases) <> ")")

renderRecordAlias :: Text -> [FieldIR] -> [Text]
renderRecordAlias name fields =
    ["export type " <> name <> " = " <> recordType fields <> ";"]
        <> renderCodec name (recordGuardExpression fields)

renderWireAlias :: Text -> WireIR -> [Text]
renderWireAlias name wire =
    ["export type " <> name <> " = " <> wireType wire <> ";"]
        <> renderCodec name (valueGuard "value" wire)

renderCodec :: Text -> Text -> [Text]
renderCodec name guardExpression =
    [ "export function is" <> name <> "(value: unknown): value is " <> name <> " {"
    , "    return " <> guardExpression <> ";"
    , "}"
    , "export function parse" <> name <> "(value: unknown): " <> name <> " {"
    , "    if (is" <> name <> "(value)) return value;"
    , "    throw new Error(\"Invalid " <> name <> "\");"
    , "}"
    , "export function encode" <> name <> "(value: " <> name <> "): " <> name <> " { return value; }"
    , ""
    ]

renderUnionValues :: [Text] -> [Text]
renderUnionValues values =
    case values of
        [] -> ["    never;", ""]
        _  -> zipWith render values [0 :: Int ..]
    where
        render value index = (if index == 0 then "    " else "  | ") <> quote value <> if index == length values - 1 then ";" else ""

renderUnionCases :: Text -> [UnionCaseIR] -> [Text]
renderUnionCases discriminator cases =
    case cases of
        [] -> ["    never;", ""]
        _  -> zipWith render cases [0 :: Int ..]
    where
        render caseIR index =
            (if index == 0 then "    " else "  | ") <> (recordType (FieldIR "Discriminator" discriminator (WireRefIR (quote caseIR.unionCaseTag)) RequiredField : caseIR.unionCaseFields)) <> if index == length cases - 1 then ";" else ""

recordType :: [FieldIR] -> Text
recordType fields = "{ " <> Text.intercalate "; " (fmap renderField fields) <> " }"

renderField :: FieldIR -> Text
renderField field =
    propertyName field.fieldName <> optionalMarker field.fieldPresence <> ": " <> wireType field.fieldWire <> nullableSuffix field.fieldPresence

wireType :: WireIR -> Text
wireType = \case
    WireTextIR -> "string"
    WireIntIR -> "number"
    WireBoolIR -> "boolean"
    WireUuidIR -> wirePrimitiveTypeName WireUuidIR
    WireDayIR -> wirePrimitiveTypeName WireDayIR
    WireUnknownIR -> "unknown"
    WireListIR inner -> "ReadonlyArray<" <> wireType inner <> ">"
    WireMapIR key value -> "Record<" <> wireType key <> ", " <> wireType value <> ">"
    WireOptionalIR inner -> wireType inner <> " | undefined"
    WireNullableIR inner -> wireType inner <> " | null"
    WireRefIR name | Text.isPrefixOf "\"" name -> name
    WireRefIR name -> name
    WireSurfaceScopeIR -> "SurfaceScope"
    WireSurfaceFragmentKeyIR -> "SurfaceFragmentKey"
    WireSurfaceWireFragmentIR -> "SurfaceWireFragment"

optionalMarker :: FieldPresence -> Text
optionalMarker = \case
    OptionalFieldPresence -> "?"
    RequiredField -> ""
    NullableFieldPresence -> ""

nullableSuffix :: FieldPresence -> Text
nullableSuffix = \case
    NullableFieldPresence -> " | null"
    RequiredField -> ""
    OptionalFieldPresence -> ""

recordGuardExpression :: [FieldIR] -> Text
recordGuardExpression fields =
    "isRecord(value)" <> mconcat (fmap fieldGuard fields)
    where
        fieldGuard field =
            let access = "value[" <> quote field.fieldName <> "]"
             in case field.fieldPresence of
                    RequiredField -> " && (" <> valueGuard access field.fieldWire <> ")"
                    OptionalFieldPresence -> " && (!(" <> quote field.fieldName <> " in value) || (" <> valueGuard access field.fieldWire <> "))"
                    NullableFieldPresence -> " && (" <> access <> " === null || (" <> valueGuard access field.fieldWire <> "))"

valueGuard :: Text -> WireIR -> Text
valueGuard access = \case
    WireTextIR -> "typeof " <> access <> " === \"string\""
    WireIntIR -> "typeof " <> access <> " === \"number\" && Number.isInteger(" <> access <> ")"
    WireBoolIR -> "typeof " <> access <> " === \"boolean\""
    WireUuidIR -> primitiveValueGuard access WireUuidIR
    WireDayIR -> primitiveValueGuard access WireDayIR
    WireUnknownIR -> "true"
    WireListIR inner -> "Array.isArray(" <> access <> ") && " <> access <> ".every((item) => " <> valueGuard "item" inner <> ")"
    WireMapIR key value -> "isRecord(" <> access <> ") && Object.entries(" <> access <> ").every(([key, entry]) => " <> valueGuard "key" key <> " && " <> valueGuard "entry" value <> ")"
    WireOptionalIR inner -> access <> " === undefined || " <> valueGuard access inner
    WireNullableIR inner -> access <> " === null || " <> valueGuard access inner
    WireRefIR name | Text.isPrefixOf "\"" name -> access <> " === " <> name
    WireRefIR name -> "is" <> name <> "(" <> access <> ")"
    WireSurfaceScopeIR -> "isSurfaceScope(" <> access <> ")"
    WireSurfaceFragmentKeyIR -> "isSurfaceFragmentKey(" <> access <> ")"
    WireSurfaceWireFragmentIR -> "isSurfaceWireFragment(" <> access <> ")"

primitiveValueGuard :: Text -> WireIR -> Text
primitiveValueGuard access wire = "typeof " <> access <> " === " <> quote (wirePrimitiveRuntimeType wire)

isEnumExpression :: [Text] -> Text
isEnumExpression values = "typeof value === \"string\" && [" <> Text.intercalate ", " (fmap quote values) <> "].includes(value)"

caseGuard :: Text -> UnionCaseIR -> Text
caseGuard discriminator caseIR = "(isRecord(value) && value[" <> quote discriminator <> "] === " <> quote caseIR.unionCaseTag <> Text.drop (Text.length "isRecord(value)") (recordGuardExpression caseIR.unionCaseFields) <> ")"

surfaceTypePrefix :: SurfaceIR -> Text
surfaceTypePrefix surface = typeNameFromMarker surface.surfaceMarker

protocolTypeName :: Text -> Text
protocolTypeName name =
    name
        |> Text.splitOn "-"
        |> filter (not . Text.null)
        |> fmap title
        |> mconcat
    where
        title text =
            case Text.uncons text of
                Nothing -> ""
                Just (firstChar, rest) -> Text.singleton (Char.toUpper firstChar) <> rest

typeNameFromMarker :: Text -> Text
typeNameFromMarker marker
    | "-" `Text.isInfixOf` marker =
        marker
            |> Text.splitOn "-"
            |> filter (not . Text.null)
            |> fmap title
            |> mconcat
    | otherwise = Text.filter (/= '-') marker
    where
        title text =
            case Text.uncons text of
                Nothing -> ""
                Just (firstChar, rest) -> Text.singleton (Char.toUpper firstChar) <> rest

constName :: Text -> Text
constName marker =
    case Text.uncons (typeNameFromMarker marker) of
        Nothing -> "contract"
        Just (firstChar, rest) -> Text.singleton (Char.toLower firstChar) <> rest

propertyName :: Text -> Text
propertyName name
    | Text.all isIdentifierChar name && maybe False isIdentifierStart (fst <$> Text.uncons name) = name
    | otherwise = quote name
    where
        isIdentifierStart char = Char.isAlpha char || char == '_'
        isIdentifierChar char = Char.isAlphaNum char || char == '_'

quote :: Text -> Text
quote value = "\"" <> Text.replace "\\" "\\\\" (Text.replace "\"" "\\\"" value) <> "\""
