{-# LANGUAGE LambdaCase          #-}
{-# LANGUAGE NoImplicitPrelude   #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings   #-}

module Application.Helper.FrontendContract.TypeScript
    ( renderFrontendContractTypeScript
    ) where

import Application.Helper.FrontendContract.IR
import qualified Data.Char as Char
import qualified Data.List as List
import qualified Data.Text as Text
import IHP.Prelude

renderFrontendContractTypeScript :: FrontendContractIR -> Either Text Text
renderFrontendContractTypeScript contract = do
    checked <- case checkedFrontendContractIR contract of
        Right value -> Right value
        Left diagnostics -> Left (Text.intercalate "\n" (fmap (.diagnosticMessage) diagnostics))
    pure (Text.unlines (header checked <> renderDerivedSurfaceWireTypes checked.contractSurfaces <> concatMap renderGlobal checked.contractGlobals <> concatMap renderSurface checked.contractSurfaces <> renderFrontendSurfaceRuntime checked.contractSurfaces))

data WirePrimitiveTypeScript = WirePrimitiveTypeScript
    { primitiveWire      :: !WireIR
    , primitiveTypeName  :: !Text
    , primitiveTsRuntime :: !Text
    }

wirePrimitiveTypes :: [WirePrimitiveTypeScript]
wirePrimitiveTypes =
    [ WirePrimitiveTypeScript WireUuidIR "FrontendContractUuid" "string"
    , WirePrimitiveTypeScript WireDayIR "FrontendContractDay" "string"
    ]

wirePrimitiveTypeName :: WireIR -> Text
wirePrimitiveTypeName wire =
    case List.find ((== wire) . (.primitiveWire)) wirePrimitiveTypes of
        Just primitive -> primitive.primitiveTypeName
        Nothing        -> error ("No TypeScript primitive alias registered for " <> show wire)

wirePrimitiveRuntimeType :: WireIR -> Text
wirePrimitiveRuntimeType wire =
    case List.find ((== wire) . (.primitiveWire)) wirePrimitiveTypes of
        Just primitive -> primitive.primitiveTsRuntime
        Nothing        -> error ("No TypeScript primitive runtime type registered for " <> show wire)

renderWirePrimitiveAliases :: FrontendContractIR -> [Text]
renderWirePrimitiveAliases contract =
    [ "export type " <> primitive.primitiveTypeName <> " = " <> primitive.primitiveTsRuntime <> ";"
    | primitive <- wirePrimitiveTypes
    , any (wireContains primitive.primitiveWire) (browserReachableWires contract)
    ]

browserReachableWires :: FrontendContractIR -> [WireIR]
browserReachableWires contract =
    concatMap globalWires contract.contractGlobals
        <> concatMap surfaceWires contract.contractSurfaces
  where
    globalWires global = concatMap primitiveWires global.globalPrimitives
    primitiveWires = \case
        GlobalSchemaIR BrowserUnreachableIR _ -> []
        GlobalSchemaIR _ schema -> fmap (.fieldWire) (schemaFields schema)
        GlobalEventIR BrowserUnreachableIR _ _ _ -> []
        GlobalEventIR BrowserTypeOnlyIR _ _ _ -> []
        GlobalEventIR _ _ _ fields -> fmap (.fieldWire) fields
        _ -> []
    surfaceWires surface =
        fmap (.fieldWire)
            ( concatMap (.scopeFields) surface.surfaceScopes
                <> concatMap (.fragmentParams) surface.surfaceFragments
                <> concatMap reachableDtoFields surface.surfaceDtos
            )
    reachableDtoFields dto =
        case dto.surfaceDtoReachability of
            BrowserUnreachableIR -> []
            _                    -> schemaFields dto.surfaceDtoSchema

wireContains :: WireIR -> WireIR -> Bool
wireContains expected wire
    | expected == wire = True
wireContains expected (WireListIR inner) = wireContains expected inner
wireContains expected (WireMapIR key value) = wireContains expected key || wireContains expected value
wireContains expected (WireOptionalIR inner) = wireContains expected inner
wireContains expected (WireNullableIR inner) = wireContains expected inner
wireContains _ _ = False

header :: FrontendContractIR -> [Text]
header contract =
    [ "// Generated by Application.Helper.FrontendContract. Do not edit." ]
        <> renderWirePrimitiveAliases contract
        <> [ ""
           , "function isRecord(value: unknown): value is Record<string, unknown> {"
           , "    return typeof value === \"object\" && value !== null && !Array.isArray(value);"
           , "}"
           , "function hasExactKeys(value: Record<string, unknown>, keys: readonly string[], requiredKeys: readonly string[] = keys): boolean {"
           , "    const valueKeys = Object.keys(value);"
           , "    return valueKeys.every((key) => keys.includes(key)) && requiredKeys.every((key) => Object.prototype.hasOwnProperty.call(value, key));"
           , "}"
           , ""
           ]

semanticSurfaceFieldName, semanticScopeFieldName, semanticKindFieldName, semanticParamsFieldName :: Text
semanticSurfaceFieldName = surfaceWireFieldName SurfaceWireSurfaceField
semanticScopeFieldName = surfaceWireFieldName SurfaceWireScopeField
semanticKindFieldName = surfaceWireFieldName SurfaceWireKindField
semanticParamsFieldName = surfaceWireFieldName SurfaceWireParamsField

renderDerivedSurfaceWireTypes :: [SurfaceIR] -> [Text]
renderDerivedSurfaceWireTypes surfaces =
    concatMap renderSurfaceScopeUnion surfaces
        <> concatMap renderSurfaceFragmentKeyUnion surfaces
        <> renderTopLevelSurfaceScopeUnion surfaces
        <> renderTopLevelSurfaceFragmentKeyUnion surfaces
        <> renderTopLevelInteractionSurfaceVocabulary surfaces

renderSurfaceScopeUnion :: SurfaceIR -> [Text]
renderSurfaceScopeUnion surface =
    [ "export type " <> surfaceScopeUnionName surface <> " =" ]
        <> renderNamedUnion scopeTypes
        <> renderGuard (surfaceScopeUnionName surface) (orExpression ["is" <> scopeType <> "(value)" | scopeType <- scopeTypes])
    where
        scopeTypes = [surfaceScopeTypeName surface scope.scopeMarker | scope <- surface.surfaceScopes]

renderSurfaceFragmentKeyUnion :: SurfaceIR -> [Text]
renderSurfaceFragmentKeyUnion surface =
    [ "export type " <> surfaceFragmentKeyUnionName surface <> " =" ]
        <> renderFragmentKeyCases surface fragments
        <> renderGuard (surfaceFragmentKeyUnionName surface) (orExpression (fmap (fragmentKeyGuard surface) fragments))
    where
        fragments = [(fragment.fragmentMarker, fragment.fragmentName, fragment.fragmentParams) | fragment <- surface.surfaceFragments]

renderTopLevelSurfaceScopeUnion :: [SurfaceIR] -> [Text]
renderTopLevelSurfaceScopeUnion surfaces =
    [ "export type SurfaceScope =" ]
        <> renderSurfaceScopeCases surfaces
        <> renderGuard "SurfaceScope" (orExpression (fmap surfaceScopeCaseGuard surfaces))

renderTopLevelSurfaceFragmentKeyUnion :: [SurfaceIR] -> [Text]
renderTopLevelSurfaceFragmentKeyUnion surfaces =
    [ "export type SurfaceFragmentKey =" ]
        <> renderTopLevelFragmentKeyCases surfaces
        <> renderGuard "SurfaceFragmentKey" (orExpression (fmap surfaceFragmentKeyCaseGuard surfaces))
        <> [ "function __canonicalFrontendContractJson(value: unknown): string {"
           , "    if (Array.isArray(value)) return `[${value.map(__canonicalFrontendContractJson).join(\",\")}]`;"
           , "    if (isRecord(value)) return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${__canonicalFrontendContractJson(value[key])}`).join(\",\")}}`;"
           , "    return JSON.stringify(value) ?? \"null\";"
           , "}"
           , "export function surfaceFragmentKeyIdentity(value: SurfaceFragmentKey): string {"
           , "    return __canonicalFrontendContractJson([value." <> semanticSurfaceFieldName <> ", value." <> semanticKindFieldName <> ", value." <> semanticParamsFieldName <> "]);"
           , "}"
           , "export function surfaceFragmentKeysEqual(left: SurfaceFragmentKey, right: SurfaceFragmentKey): boolean {"
           , "    return surfaceFragmentKeyIdentity(left) === surfaceFragmentKeyIdentity(right);"
           , "}"
           , ""
           ]

renderTopLevelInteractionSurfaceVocabulary :: [SurfaceIR] -> [Text]
renderTopLevelInteractionSurfaceVocabulary surfaces =
    renderTopLevelStringUnion "FrontendSurfaceInteractionSurfaceName" (fmap (.surfaceName) interactionSurfaces)
    where
        interactionSurfaces = filter surfaceHasBrowserInteraction surfaces

renderTopLevelStringUnion :: Text -> [Text] -> [Text]
renderTopLevelStringUnion typeName rawValues =
    [ "export type " <> typeName <> " = " <> renderStringUnion values <> ";"
    , "export function is" <> typeName <> "(value: unknown): value is " <> typeName <> " {"
    , "    return typeof value === \"string\" && [" <> Text.intercalate ", " (fmap quote values) <> "].includes(value);"
    , "}"
    , ""
    ]
    where
        values = List.nub rawValues

renderStringUnion :: [Text] -> Text
renderStringUnion values =
    case values of
        [] -> "never"
        _  -> Text.intercalate " | " (fmap quote values)

renderNamedUnion :: [Text] -> [Text]
renderNamedUnion names =
    case names of
        [] -> ["    never;", ""]
        _  -> zipWith render names [0 :: Int ..]
    where
        render name index = (if index == 0 then "    " else "  | ") <> name <> if index == length names - 1 then ";" else ""

renderSurfaceScopeCases :: [SurfaceIR] -> [Text]
renderSurfaceScopeCases surfaces =
    case surfaces of
        [] -> ["    never;", ""]
        _  -> zipWith render surfaces [0 :: Int ..]
    where
        render surface index =
            (if index == 0 then "    " else "  | ") <> "{ " <> semanticSurfaceFieldName <> ": " <> quote surface.surfaceName <> "; " <> semanticScopeFieldName <> ": " <> surfaceScopeUnionName surface <> " }" <> if index == length surfaces - 1 then ";" else ""

renderFragmentKeyCases :: SurfaceIR -> [(Text, Text, [FieldIR])] -> [Text]
renderFragmentKeyCases _ [] = ["    never;", ""]
renderFragmentKeyCases surface fragments = zipWith render fragments [0 :: Int ..]
    where
        render (marker, fragmentName, fields) index =
            (if index == 0 then "    " else "  | ") <> "{ " <> semanticKindFieldName <> ": " <> quote fragmentName <> "; " <> semanticParamsFieldName <> ": " <> fragmentParamsType surface marker fields <> " }" <> if index == length fragments - 1 then ";" else ""

renderTopLevelFragmentKeyCases :: [SurfaceIR] -> [Text]
renderTopLevelFragmentKeyCases [] = ["    never;", ""]
renderTopLevelFragmentKeyCases surfaces = zipWith render surfaces [0 :: Int ..]
    where
        render surface index =
            (if index == 0 then "    " else "  | ") <> "({ " <> semanticSurfaceFieldName <> ": " <> quote surface.surfaceName <> " } & " <> surfaceFragmentKeyUnionName surface <> ")" <> if index == length surfaces - 1 then ";" else ""

surfaceScopeCaseGuard :: SurfaceIR -> Text
surfaceScopeCaseGuard surface =
    "(isRecord(value) && hasExactKeys(value, ["
        <> quote semanticSurfaceFieldName
        <> ", "
        <> quote semanticScopeFieldName
        <> "]) && value."
        <> semanticSurfaceFieldName
        <> " === "
        <> quote surface.surfaceName
        <> " && is"
        <> surfaceScopeUnionName surface
        <> "(value."
        <> semanticScopeFieldName
        <> "))"

surfaceFragmentKeyCaseGuard :: SurfaceIR -> Text
surfaceFragmentKeyCaseGuard surface =
    "(isRecord(value) && hasExactKeys(value, ["
        <> Text.intercalate ", " (fmap quote [semanticSurfaceFieldName, semanticKindFieldName, semanticParamsFieldName])
        <> "]) && value."
        <> semanticSurfaceFieldName
        <> " === "
        <> quote surface.surfaceName
        <> " && is"
        <> surfaceFragmentKeyUnionName surface
        <> "({ "
        <> semanticKindFieldName
        <> ": value."
        <> semanticKindFieldName
        <> ", "
        <> semanticParamsFieldName
        <> ": value."
        <> semanticParamsFieldName
        <> " }))"

fragmentKeyGuard :: SurfaceIR -> (Text, Text, [FieldIR]) -> Text
fragmentKeyGuard _surface (_marker, fragmentName, fields) =
    "(isRecord(value) && hasExactKeys(value, ["
        <> Text.intercalate ", " (fmap quote [semanticKindFieldName, semanticParamsFieldName])
        <> "]) && value."
        <> semanticKindFieldName
        <> " === "
        <> quote fragmentName
        <> " && ("
        <> paramsGuard
        <> "))"
    where
        paramsAccess = "value[" <> quote semanticParamsFieldName <> "]"
        paramsGuard
            | null fields = paramsAccess <> " === null || " <> recordGuardExpressionWithAccess paramsAccess fields
            | otherwise = recordGuardExpressionWithAccess paramsAccess fields

recordGuardExpressionWithAccess :: Text -> [FieldIR] -> Text
recordGuardExpressionWithAccess access fields = Text.replace "value" access (recordGuardExpression fields)

fragmentParamsType :: SurfaceIR -> Text -> [FieldIR] -> Text
fragmentParamsType surface marker fields
    | null fields = surfaceFragmentParamsTypeName surface marker <> " | null"
    | otherwise = surfaceFragmentParamsTypeName surface marker

orExpression :: [Text] -> Text
orExpression expressions =
    case expressions of
        [] -> "false"
        _  -> "(" <> Text.intercalate " || " expressions <> ")"

surfaceScopeUnionName :: SurfaceIR -> Text
surfaceScopeUnionName surface = surfaceTypePrefix surface <> "SurfaceScope"

surfaceFragmentKeyUnionName :: SurfaceIR -> Text
surfaceFragmentKeyUnionName surface = surfaceTypePrefix surface <> "SurfaceFragmentKey"

surfaceScopeTypeName :: SurfaceIR -> Text -> Text
surfaceScopeTypeName surface marker = surfaceTypePrefix surface <> typeNameFromMarker marker <> "Scope"

surfaceFragmentParamsTypeName :: SurfaceIR -> Text -> Text
surfaceFragmentParamsTypeName surface marker = surfaceTypePrefix surface <> typeNameFromMarker marker <> "FragmentParams"

renderGlobal :: GlobalIR -> [Text]
renderGlobal global =
    concatMap renderGlobalPrimitive global.globalPrimitives
        <> concatMap (renderGlobalProjection global.globalPrimitives) [projection | GlobalProjectionIR projection <- global.globalPrimitives]

renderGlobalPrimitive :: GlobalPrimitiveIR -> [Text]
renderGlobalPrimitive = \case
    GlobalSchemaIR BrowserUnreachableIR _ -> []
    GlobalSchemaIR reachability schema -> renderSchemaFor reachability schema
    GlobalEventIR BrowserUnreachableIR _ _ _ -> []
    GlobalEventIR reachability marker eventName fields ->
        renderEventDetail reachability (typeNameFromMarker marker <> "EventDetail") fields
            <> ["export const " <> constName marker <> "Event = " <> quote eventName <> " as const;", ""]
    GlobalDomIdIR marker domId -> ["export const " <> constName marker <> "DomId = " <> quote domId <> " as const;", ""]
    GlobalServerDomIdIR _ _ -> []
    GlobalDomAttrIR marker attr -> ["export const " <> constName marker <> "DomAttr = " <> quote attr <> " as const;", ""]
    GlobalServerDomAttrIR _ _ -> []
    GlobalDomValueIR marker value -> ["export const " <> constName marker <> "DomValue = " <> quote value <> " as const;", ""]
    GlobalFieldNameIR marker name -> ["export const " <> constName marker <> "FieldName = " <> quote name <> " as const;", ""]
    GlobalDomTokenIR marker token -> ["export const " <> constName marker <> "DomToken = " <> quote token <> " as const;", ""]
    GlobalConstantIR marker value -> ["export const " <> constName marker <> " = " <> quote value <> " as const;", ""]
    GlobalProjectionIR _ -> []
    GlobalAppShellActionIR _ -> []

renderGlobalProjection :: [GlobalPrimitiveIR] -> GlobalProjectionIR -> [Text]
renderGlobalProjection primitives = \case
    InteractionDomProjectionIR -> renderInteractionDomGroup primitives

renderInteractionDomGroup :: [GlobalPrimitiveIR] -> [Text]
renderInteractionDomGroup primitives =
    [ "export type InteractionDomAttributes = {"
    ]
        <> fmap renderAttrType attrs
        <> [ "};"
           , "export type InteractionDomValues = {"
           ]
        <> fmap renderValueType values
        <> [ "};"
           , "export type InteractionPointerFields = {"
           ]
        <> fmap renderFieldType fields
        <> [ "};"
           , "export type InteractionDom = { attributes: InteractionDomAttributes; values: InteractionDomValues; pointerFields: InteractionPointerFields };"
           , "export const InteractionDom: InteractionDom = {"
           , "    attributes: { " <> Text.intercalate ", " (fmap renderAttrValue attrs) <> " },"
           , "    values: { " <> Text.intercalate ", " (fmap renderDomValue values) <> " },"
           , "    pointerFields: { " <> Text.intercalate ", " (fmap renderFieldValue fields) <> " },"
           , "};"
           , ""
           ]
    where
        attrs = [(marker, value) | GlobalDomAttrIR marker value <- primitives]
        values = [(marker, value) | GlobalDomValueIR marker value <- primitives]
        fields = [(marker, value) | GlobalFieldNameIR marker value <- primitives]
        renderAttrType (marker, _) = "    " <> constName marker <> ": typeof " <> constName marker <> "DomAttr;"
        renderValueType (marker, _) = "    " <> constName marker <> ": typeof " <> constName marker <> "DomValue;"
        renderFieldType (marker, _) = "    " <> constName marker <> ": typeof " <> constName marker <> "FieldName;"
        renderAttrValue (marker, _) = constName marker <> ": " <> constName marker <> "DomAttr"
        renderDomValue (marker, _) = constName marker <> ": " <> constName marker <> "DomValue"
        renderFieldValue (marker, _) = constName marker <> ": " <> constName marker <> "FieldName"

renderSurface :: SurfaceIR -> [Text]
renderSurface surface =
    concatMap renderSurfaceDto surface.surfaceDtos
        <> concatMap (renderScope surface) surface.surfaceScopes
        <> concatMap (renderFragment surface) surface.surfaceFragments

renderSurfaceDto :: SurfaceDtoIR -> [Text]
renderSurfaceDto dto =
    case dto.surfaceDtoReachability of
        BrowserUnreachableIR -> []
        reachability -> renderSchemaFor reachability dto.surfaceDtoSchema

renderFrontendSurfaceRuntime :: [SurfaceIR] -> [Text]
renderFrontendSurfaceRuntime surfaces =
    renderFrontendSurfaceBrandAliases surfaces
        <> concatMap renderFrontendSurfaceDomTokenConstants surfaces
        <> concatMap renderFrontendSurfaceBrowserAttributeConstants surfaces
        <> concatMap renderFrontendSurfaceBrowserClosedStateTypes surfaces
        <> concatMap renderFrontendSurfaceCompleteSetSortKeyTypes surfaces
        <> concatMap renderFrontendSurfaceTabSetKeyTypes surfaces
        <> renderFrontendSurfaceRegistries surfaces
        <> renderFrontendSurfaceMountConfigTypes surfaces

renderFrontendSurfaceBrandAliases :: [SurfaceIR] -> [Text]
renderFrontendSurfaceBrandAliases surfaces =
    [ "export type " <> alias <> " = " <> wirePrimitiveTypeName WireUuidIR <> ";"
    | alias <- List.nub (concatMap surfaceUuidAliases surfaces)
    ] <> ["" | not (null (concatMap surfaceUuidAliases surfaces))]

surfaceUuidAliases :: SurfaceIR -> [Text]
surfaceUuidAliases surface =
    [ typeNameFromMarker field.fieldMarker
    | field <- surfaceFields surface
    , isUuidWire field.fieldWire
    ]

surfaceFields :: SurfaceIR -> [FieldIR]
surfaceFields surface =
    concatMap (.scopeFields) surface.surfaceScopes
        <> concatMap (.fragmentParams) surface.surfaceFragments
        <> concatMap (.htmxActionFields) surface.surfaceHtmxActions
        <> concatMap (.intentFields) surface.surfaceIntents
        <> concatMap snd surface.surfaceClientEvents
        <> concatMap reachableDtoFields surface.surfaceDtos
  where
    reachableDtoFields dto =
        case dto.surfaceDtoReachability of
            BrowserUnreachableIR -> []
            _                    -> schemaFields dto.surfaceDtoSchema

isUuidWire :: WireIR -> Bool
isUuidWire = \case
    WireUuidIR -> True
    WireOptionalIR inner -> isUuidWire inner
    WireNullableIR inner -> isUuidWire inner
    WireListIR inner -> isUuidWire inner
    _ -> False

renderFrontendSurfaceDomTokenConstants :: SurfaceIR -> [Text]
renderFrontendSurfaceDomTokenConstants surface =
    [ "export const " <> constName token <> "DomToken = " <> quote token <> " as const;"
    | token <- surface.surfaceBrowserDomTokens
    ] <> ["" | not (null surface.surfaceBrowserDomTokens)]

renderFrontendSurfaceBrowserAttributeConstants :: SurfaceIR -> [Text]
renderFrontendSurfaceBrowserAttributeConstants surface =
    [ "export const " <> surfaceBrowserAttributeConstName surface attribute <> " = " <> quote attribute.browserAttributeDomAttribute <> " as const;"
    | attribute <- surface.surfaceBrowserRoles <> surface.surfaceBrowserStates
    ] <> ["" | not (null surface.surfaceBrowserRoles && null surface.surfaceBrowserStates)]

renderFrontendSurfaceBrowserClosedStateTypes :: SurfaceIR -> [Text]
renderFrontendSurfaceBrowserClosedStateTypes surface =
    concatMap renderState surface.surfaceBrowserClosedStates
  where
    renderState state =
        let stateType = surfaceBrowserClosedStateTypeName surface state
         in [ "export const " <> surfaceBrowserClosedStateValuesConstName surface state <> " = "
                <> objectLiteral [(value, quote value) | value <- state.browserClosedStateValues]
                <> " as const;"
            , "export type " <> stateType <> " = " <> renderStringUnion state.browserClosedStateValues <> ";"
            , "export function is" <> stateType <> "(value: unknown): value is " <> stateType <> " {"
            , "    return typeof value === \"string\" && " <> arrayLiteral (map quote state.browserClosedStateValues) <> ".includes(value);"
            , "}"
            , ""
            ]

surfaceBrowserClosedStateTypeName :: SurfaceIR -> BrowserClosedStateIR -> Text
surfaceBrowserClosedStateTypeName surface state =
    typeNameFromMarker (surface.surfaceName <> "-" <> state.browserClosedStateAttribute.browserAttributeName <> "-state")

surfaceBrowserClosedStateValuesConstName :: SurfaceIR -> BrowserClosedStateIR -> Text
surfaceBrowserClosedStateValuesConstName surface state =
    constName (surface.surfaceName <> "-" <> state.browserClosedStateAttribute.browserAttributeName <> "-states")

surfaceBrowserAttributeConstName :: SurfaceIR -> BrowserAttributeIR -> Text
surfaceBrowserAttributeConstName surface attribute =
    constName (surface.surfaceName <> "-" <> attribute.browserAttributeName) <> "DomAttr"

renderFrontendSurfaceRegistries :: [SurfaceIR] -> [Text]
renderFrontendSurfaceRegistries surfaces =
    ["export type FrontendSurfaceName = " <> renderStringUnion (fmap (.surfaceName) surfaces) <> ";"]
        <> renderFrontendSurfaceLinkedHighlightContracts surfaces
        <> renderFrontendSurfaceCompleteSetSortContracts surfaces
        <> renderFrontendSurfaceTabSetContracts surfaces
        <> renderFrontendSurfaceSidePanelContracts surfaces
        <> [ "export const FrontendSurfaceFragmentRegistry = " <> objectLiteral fragmentEntries <> " as const;"
           , "export function isFrontendSurfaceName(value: unknown): value is FrontendSurfaceName {"
           , "    return typeof value === \"string\" && Object.prototype.hasOwnProperty.call(FrontendSurfaceFragmentRegistry, value);"
           , "}"
           , "export function isFrontendSurfaceLiveFragmentName(surface: FrontendSurfaceName, value: unknown): value is string {"
           , "    return typeof value === \"string\" && (FrontendSurfaceFragmentRegistry[surface] as readonly string[]).includes(value);"
           , "}"
           , "export const FrontendSurfaceInteractionRegistry = " <> objectLiteral interactionEntries <> " as const;"
           , ""
           ]
  where
    fragmentEntries =
        [ (surface.surfaceName, arrayLiteral (fmap quote (surfaceLiveFragmentNames surface)))
        | surface <- surfaces
        ]
    interactionEntries =
        [ (surface.surfaceName, renderFrontendSurfaceInteractionDefinition surface)
        | surface <- surfaces
        , surfaceHasBrowserInteraction surface
        ]

renderFrontendSurfaceTabSetKeyTypes :: SurfaceIR -> [Text]
renderFrontendSurfaceTabSetKeyTypes surface =
    concatMap renderKeyType surface.surfaceTabSets
  where
    renderKeyType tabSet = renderTopLevelStringUnion (tabSetKeyTypeName tabSet) tabSet.tabSetKeys

tabSetKeyTypeName :: TabSetIR -> Text
tabSetKeyTypeName tabSet = typeNameFromMarker tabSet.tabSetMarker <> "Key"

renderFrontendSurfaceTabSetContracts :: [SurfaceIR] -> [Text]
renderFrontendSurfaceTabSetContracts surfaces =
    [ "export type FrontendSurfaceTabSetDefinition = { name: string; tabRoleAttribute: string; keys: ReadonlyArray<string>; defaultKey: string; isKey: (value: unknown) => boolean };"
    , "export const FrontendSurfaceTabSetRegistry: Record<FrontendSurfaceName, ReadonlyArray<FrontendSurfaceTabSetDefinition>> = " <> objectLiteral entries <> ";"
    , ""
    ]
  where
    entries =
        [ (surface.surfaceName, arrayLiteral (map (renderTabSet surface) surface.surfaceTabSets))
        | surface <- surfaces
        ]

renderTabSet :: SurfaceIR -> TabSetIR -> Text
renderTabSet surface tabSet = objectLiteral
    [ ("name", quote tabSet.tabSetName)
    , ("tabRoleAttribute", surfaceBrowserAttributeConstName surface tabSet.tabSetRole)
    , ("keys", arrayLiteral (map quote tabSet.tabSetKeys))
    , ("defaultKey", quote tabSet.tabSetDefaultKey)
    , ("isKey", "is" <> tabSetKeyTypeName tabSet)
    ]

renderFrontendSurfaceSidePanelContracts :: [SurfaceIR] -> [Text]
renderFrontendSurfaceSidePanelContracts surfaces =
    [ "export type FrontendSurfaceSidePanelDefinition = { name: string; rootRoleAttribute: string; mainRoleAttribute: string; panelRoleAttribute: string; toggleRoleAttribute: string; labelRoleAttribute: string; stateAttribute: string; collapsedValue: string; expandedValue: string; isState: (value: unknown) => boolean };"
    , "export const FrontendSurfaceSidePanelRegistry: Record<FrontendSurfaceName, ReadonlyArray<FrontendSurfaceSidePanelDefinition>> = " <> objectLiteral entries <> ";"
    , ""
    ]
  where
    entries =
        [ (surface.surfaceName, arrayLiteral (map (renderSidePanel surface) surface.surfaceSidePanels))
        | surface <- surfaces
        ]

renderSidePanel :: SurfaceIR -> SidePanelIR -> Text
renderSidePanel surface sidePanel = objectLiteral
    [ ("name", quote sidePanel.sidePanelName)
    , ("rootRoleAttribute", surfaceBrowserAttributeConstName surface sidePanel.sidePanelRootRole)
    , ("mainRoleAttribute", surfaceBrowserAttributeConstName surface sidePanel.sidePanelMainRole)
    , ("panelRoleAttribute", surfaceBrowserAttributeConstName surface sidePanel.sidePanelPanelRole)
    , ("toggleRoleAttribute", surfaceBrowserAttributeConstName surface sidePanel.sidePanelToggleRole)
    , ("labelRoleAttribute", surfaceBrowserAttributeConstName surface sidePanel.sidePanelLabelRole)
    , ("stateAttribute", surfaceBrowserAttributeConstName surface sidePanel.sidePanelState.browserClosedStateAttribute)
    , ("collapsedValue", quote sidePanel.sidePanelCollapsedValue)
    , ("expandedValue", quote sidePanel.sidePanelExpandedValue)
    , ("isState", "is" <> surfaceBrowserClosedStateTypeName surface sidePanel.sidePanelState)
    ]

renderFrontendSurfaceCompleteSetSortKeyTypes :: SurfaceIR -> [Text]
renderFrontendSurfaceCompleteSetSortKeyTypes surface =
    concatMap renderKeyType surface.surfaceCompleteSetSorts
  where
    renderKeyType sortDefinition =
        renderTopLevelStringUnion
            (completeSetSortKeyTypeName sortDefinition)
            (map (.completeSetSortKeyName) sortDefinition.completeSetSortKeys)

completeSetSortKeyTypeName :: CompleteSetSortIR -> Text
completeSetSortKeyTypeName sortDefinition = typeNameFromMarker sortDefinition.completeSetSortMarker <> "Key"

renderFrontendSurfaceCompleteSetSortContracts :: [SurfaceIR] -> [Text]
renderFrontendSurfaceCompleteSetSortContracts surfaces =
    [ "export type FrontendSurfaceCompleteSetSortValueType = " <> renderStringUnion valueTypeNames <> ";"
    , "export type FrontendSurfaceCompleteSetSortComparatorDirection = " <> renderStringUnion comparatorDirectionNames <> ";"
    , "export type FrontendSurfaceCompleteSetSortDirection = " <> renderStringUnion directionNames <> ";"
    , "export type FrontendSurfaceCompleteSetSortComparator = { field: string; valueType: FrontendSurfaceCompleteSetSortValueType; direction: FrontendSurfaceCompleteSetSortComparatorDirection; read: (row: unknown) => unknown };"
    , "export type FrontendSurfaceCompleteSetSortKeyDefinition = { key: string; comparators: ReadonlyArray<FrontendSurfaceCompleteSetSortComparator> };"
    , "export type FrontendSurfaceCompleteSetSortDefinition = { name: string; rootRoleAttribute: string; rowRoleAttribute: string; controlRoleAttribute: string; parseRow: (value: unknown) => unknown; isKey: (value: unknown) => boolean; keys: ReadonlyArray<FrontendSurfaceCompleteSetSortKeyDefinition>; defaultKey: string; defaultDirection: FrontendSurfaceCompleteSetSortDirection };"
    , "export const FrontendSurfaceCompleteSetSortRegistry: Record<FrontendSurfaceName, ReadonlyArray<FrontendSurfaceCompleteSetSortDefinition>> = " <> objectLiteral entries <> ";"
    , ""
    ]
  where
    valueTypeNames = map completeSetSortValueTypeName [CompleteSetSortTextIR, CompleteSetSortIntegerIR, CompleteSetSortOpaqueIR]
    comparatorDirectionNames = map completeSetSortComparatorDirectionName [CompleteSetSortSelectedDirectionIR, CompleteSetSortAscendingComparatorIR]
    directionNames = map completeSetSortDirectionName [CompleteSetSortAscendingIR, CompleteSetSortDescendingIR]
    entries =
        [ (surface.surfaceName, arrayLiteral (map (renderCompleteSetSort surface) surface.surfaceCompleteSetSorts))
        | surface <- surfaces
        ]

renderCompleteSetSort :: SurfaceIR -> CompleteSetSortIR -> Text
renderCompleteSetSort surface sortDefinition = objectLiteral
    [ ("name", quote sortDefinition.completeSetSortName)
    , ("rootRoleAttribute", surfaceBrowserAttributeConstName surface sortDefinition.completeSetSortRootRole)
    , ("rowRoleAttribute", surfaceBrowserAttributeConstName surface sortDefinition.completeSetSortRowRole)
    , ("controlRoleAttribute", surfaceBrowserAttributeConstName surface sortDefinition.completeSetSortControlRole)
    , ("parseRow", "parse" <> rowDtoName)
    , ("isKey", "is" <> completeSetSortKeyTypeName sortDefinition)
    , ("keys", arrayLiteral (map (renderCompleteSetSortKey rowDtoName) sortDefinition.completeSetSortKeys))
    , ("defaultKey", quote sortDefinition.completeSetSortDefaultKey)
    , ("defaultDirection", quote (completeSetSortDirectionName sortDefinition.completeSetSortDefaultDirection))
    ]
  where
    rowDtoName =
        case List.find ((== sortDefinition.completeSetSortRowDtoMarker) . snd . schemaNameAndMarker . (.surfaceDtoSchema)) surface.surfaceDtos of
            Just dto -> fst (schemaNameAndMarker dto.surfaceDtoSchema)
            Nothing -> error ("Missing checked complete-set sort row DTO " <> cs sortDefinition.completeSetSortRowDtoMarker)

renderCompleteSetSortKey :: Text -> CompleteSetSortKeyIR -> Text
renderCompleteSetSortKey rowDtoName key = objectLiteral
    [ ("key", quote key.completeSetSortKeyName)
    , ("comparators", arrayLiteral (map (renderCompleteSetSortComparator rowDtoName) key.completeSetSortKeyComparators))
    ]

renderCompleteSetSortComparator :: Text -> CompleteSetSortComparatorIR -> Text
renderCompleteSetSortComparator rowDtoName comparator = objectLiteral
    [ ("field", quote comparator.completeSetSortComparatorField)
    , ("valueType", quote (completeSetSortValueTypeName comparator.completeSetSortComparatorValueType))
    , ("direction", quote (completeSetSortComparatorDirectionName comparator.completeSetSortComparatorDirection))
    , ("read", "(row: unknown) => parse" <> rowDtoName <> "(row)." <> propertyName comparator.completeSetSortComparatorField)
    ]

renderFrontendSurfaceLinkedHighlightContracts :: [SurfaceIR] -> [Text]
renderFrontendSurfaceLinkedHighlightContracts surfaces =
    [ "export type FrontendSurfaceLinkedHighlightActivation = " <> renderStringUnion activationNames <> ";"
    , "export type FrontendSurfaceLinkedHighlightEffect = " <> renderStringUnion effectNames <> ";"
    , "export type FrontendSurfaceLinkedHighlightDefinition = { name: string; sourceRoleAttribute: string; memberRoleAttribute: string; pinRoleAttribute: string | null; defaultRoleAttribute: string | null; orderStateAttribute: string | null; activations: ReadonlyArray<FrontendSurfaceLinkedHighlightActivation>; effects: ReadonlyArray<FrontendSurfaceLinkedHighlightEffect> };"
    , "export const FrontendSurfaceLinkedHighlightRegistry: Record<FrontendSurfaceName, ReadonlyArray<FrontendSurfaceLinkedHighlightDefinition>> = " <> objectLiteral entries <> ";"
    , ""
    ]
  where
    emptyAttribute = BrowserAttributeIR "" "" ""
    activationNames =
        map linkedHighlightActivationName
            [ LinkedHighlightHoverActivationIR
            , LinkedHighlightFocusActivationIR
            , LinkedHighlightKeyboardActivationIR
            , LinkedHighlightPinActivationIR emptyAttribute
            , LinkedHighlightDefaultActivationIR emptyAttribute
            ]
    effectNames =
        map linkedHighlightEffectName
            [ LinkedHighlightMatchingSourceEffectIR
            , LinkedHighlightMatchingMemberEffectIR
            , LinkedHighlightOrderedMemberBoundsEffectIR emptyAttribute
            ]
    entries =
        [ (surface.surfaceName, arrayLiteral (map (renderLinkedHighlight surface) surface.surfaceLinkedHighlights))
        | surface <- surfaces
        ]

renderLinkedHighlight :: SurfaceIR -> LinkedHighlightIR -> Text
renderLinkedHighlight surface highlight = objectLiteral
    [ ("name", quote highlight.linkedHighlightName)
    , ("sourceRoleAttribute", surfaceBrowserAttributeConstName surface highlight.linkedHighlightSourceRole)
    , ("memberRoleAttribute", surfaceBrowserAttributeConstName surface highlight.linkedHighlightMemberRole)
    , ("pinRoleAttribute", maybe "null" (surfaceBrowserAttributeConstName surface) (linkedHighlightPinRole highlight))
    , ("defaultRoleAttribute", maybe "null" (surfaceBrowserAttributeConstName surface) (linkedHighlightDefaultRole highlight))
    , ("orderStateAttribute", maybe "null" (surfaceBrowserAttributeConstName surface) (linkedHighlightOrderState highlight))
    , ("activations", arrayLiteral (map (quote . linkedHighlightActivationName) highlight.linkedHighlightActivations))
    , ("effects", arrayLiteral (map (quote . linkedHighlightEffectName) highlight.linkedHighlightEffects))
    ]

linkedHighlightPinRole :: LinkedHighlightIR -> Maybe BrowserAttributeIR
linkedHighlightPinRole highlight =
    listToMaybe [attribute | LinkedHighlightPinActivationIR attribute <- highlight.linkedHighlightActivations]

linkedHighlightDefaultRole :: LinkedHighlightIR -> Maybe BrowserAttributeIR
linkedHighlightDefaultRole highlight =
    listToMaybe [attribute | LinkedHighlightDefaultActivationIR attribute <- highlight.linkedHighlightActivations]

linkedHighlightOrderState :: LinkedHighlightIR -> Maybe BrowserAttributeIR
linkedHighlightOrderState highlight =
    listToMaybe [attribute | LinkedHighlightOrderedMemberBoundsEffectIR attribute <- highlight.linkedHighlightEffects]

surfaceHasBrowserInteraction :: SurfaceIR -> Bool
surfaceHasBrowserInteraction surface =
    not (null surface.surfaceSourceRefs)
        || not (null surface.surfaceDropzoneRefs)
        || not (null surface.surfaceActivationRefs)
        || not (null surface.surfaceSessions)

renderFrontendSurfaceInteractionDefinition :: SurfaceIR -> Text
renderFrontendSurfaceInteractionDefinition surface = objectLiteral
    [ ("sourceRefs", arrayLiteral (fmap renderSourceRef surface.surfaceSourceRefs))
    , ("dropzoneRefs", arrayLiteral (fmap renderDropzoneRef surface.surfaceDropzoneRefs))
    , ("activationRefs", arrayLiteral (fmap renderActivationRef surface.surfaceActivationRefs))
    , ("sessionKinds", arrayLiteral (fmap renderBrowserSessionKind surface.surfaceSessions))
    ]

renderSourceRef :: InteractionSourceRefIR -> Text
renderSourceRef ref = objectLiteral
    [ ("ref", quote ref.sourceRefName)
    , ("session", quote ref.sourceRefSession)
    , ("intent", quote ref.sourceRefIntent)
    , ("sourceField", quote ref.sourceRefSourceField)
    , ("compatibleDropzones", arrayLiteral (fmap quote ref.sourceRefCompatibleDropzones))
    , ("modifierVariants", arrayLiteral (fmap renderModifierVariant ref.sourceRefVariants))
    ]

renderModifierVariant :: InteractionModifierVariantIR -> Text
renderModifierVariant variant = objectLiteral
    [ ("semantic", quote variant.modifierVariantSemantic)
    , ("intent", quote variant.modifierVariantIntent)
    , ("effects", renderSessionEffects variant.modifierVariantEffects)
    ]

renderDropzoneRef :: InteractionDropzoneRefIR -> Text
renderDropzoneRef ref = objectLiteral
    [ ("ref", quote ref.dropzoneRefName)
    , ("session", quote ref.dropzoneRefSession)
    , ("targetField", quote ref.dropzoneRefTargetField)
    ]

renderActivationRef :: InteractionActivationRefIR -> Text
renderActivationRef ref = objectLiteral
    [ ("ref", quote ref.activationRefName)
    , ("intent", quote ref.activationRefIntent)
    , ("valueField", maybe "null" quote ref.activationRefValueField)
    , ("trigger", quote ref.activationRefTrigger)
    ]

renderBrowserSessionKind :: InteractionSessionIR -> Text
renderBrowserSessionKind session = objectLiteral
    [ ("kind", quote session.sessionName)
    , ("effects", renderSessionEffects session.sessionEffects)
    ]

data RenderedInteractionEffect
    = RenderedGlobalInteractionEffect !Text
    | RenderedContextualInteractionEffect !Text

renderSessionEffects :: [InteractionEffectIR] -> Text
renderSessionEffects effects = objectLiteral
    [ ("global", arrayLiteral [rendered | RenderedGlobalInteractionEffect rendered <- renderedEffects])
    , ("contextual", arrayLiteral [rendered | RenderedContextualInteractionEffect rendered <- renderedEffects])
    ]
    where
        renderedEffects = fmap renderInteractionEffect effects

renderInteractionEffect :: InteractionEffectIR -> RenderedInteractionEffect
renderInteractionEffect effect =
    case effect.interactionEffectLifecycle of
        SessionGlobalEffectLifecycleIR -> RenderedGlobalInteractionEffect rendered
        ContextualTargetEffectLifecycleIR -> RenderedContextualInteractionEffect rendered
    where
        rendered = objectLiteral $
            [ ("className", quote (Text.unwords (interactionEffectClassNames effect)))
            , ("kind", quote (interactionEffectBrowserKind effect))
            ]
                <> maybe [] (\layer -> [("layer", quote layer)]) effect.interactionEffectLayer
                <> maybe [] (\preserveGrabOffset -> [("preserveGrabOffset", if preserveGrabOffset then "true" else "false")]) effect.interactionEffectPreserveGrabOffset
                <> maybe [] (\source -> [("source", quote (interactionEffectSourceName source))]) effect.interactionEffectSource

surfaceLiveFragmentNames :: SurfaceIR -> [Text]
surfaceLiveFragmentNames surface =
    [ fragment.fragmentName
    | fragment <- surface.surfaceFragments
    , optionsContainLive fragment.fragmentOptions
    ]

optionsContainLive :: [OptionIR] -> Bool
optionsContainLive = any \case
    LiveOption -> True
    LazyOption options -> optionsContainLive options
    _ -> False

objectLiteral :: [(Text, Text)] -> Text
objectLiteral fields = "{" <> Text.intercalate "," [quote key <> ":" <> value | (key, value) <- fields] <> "}"

arrayLiteral :: [Text] -> Text
arrayLiteral values = "[" <> Text.intercalate "," values <> "]"

renderFrontendSurfaceSupportSchemas :: [Text]
renderFrontendSurfaceSupportSchemas =
    renderSchemaFor BrowserGuardIR $
        TaggedUnionIR "FrontendSurfaceFragmentProtection" "FrontendSurfaceFragmentProtection" "kind"
            [ UnionCaseIR "Replace" "replace" []
            , UnionCaseIR "FocusedField" "focused-field"
                [ required "ActiveSelector" "activeSelector" WireTextIR
                , required "FieldKeyAttr" "fieldKeyAttr" WireTextIR
                , required "FieldNameFallback" "fieldNameFallback" WireBoolIR
                , nullable "ContainerSelector" "containerSelector" WireTextIR
                ]
            ]
  where
    required marker name wire = FieldIR marker name wire RequiredField
    nullable marker name wire = FieldIR marker name wire NullableFieldPresence

renderFrontendSurfaceMountConfigTypes :: [SurfaceIR] -> [Text]
renderFrontendSurfaceMountConfigTypes surfaces =
    renderFrontendSurfaceSupportSchemas
        <> [ "// FrontendSurface mount metadata is an exact surface-discriminated local envelope."
           , "// Executable URL/target/protection values exist only on these local fragment descriptors."
           ]
        <> concatMap renderFrontendSurfaceMountedFragmentConfig surfaces
        <> concatMap renderFrontendSurfaceMountConfig surfaces
        <> [ "export type FrontendSurfaceMountedFragmentConfig =" ]
        <> renderNamedUnion (fmap frontendSurfaceMountedFragmentConfigName surfaces)
        <> [ "export type FrontendSurfaceMountConfig =" ]
        <> renderNamedUnion (fmap frontendSurfaceMountConfigName surfaces)
        <> renderInboundCodec "FrontendSurfaceMountConfig" (orExpression ["is" <> frontendSurfaceMountConfigName surface <> "(value)" | surface <- surfaces])

renderFrontendSurfaceMountedFragmentConfig :: SurfaceIR -> [Text]
renderFrontendSurfaceMountedFragmentConfig surface =
    [ "export type "
        <> name
        <> " = { fragmentKey: ({ surface: "
        <> quote surface.surfaceName
        <> " } & "
        <> surfaceFragmentKeyUnionName surface
        <> "); targetId: string; url: string; protection: FrontendSurfaceFragmentProtection };"
    ]
        <> renderGuard name guardExpression
    where
        name = frontendSurfaceMountedFragmentConfigName surface
        guardExpression =
            "isRecord(value)"
                <> " && hasExactKeys(value, [\"fragmentKey\", \"targetId\", \"url\", \"protection\"])"
                <> " && isSurfaceFragmentKey(value[\"fragmentKey\"])"
                <> " && value[\"fragmentKey\"].surface === "
                <> quote surface.surfaceName
                <> " && typeof value[\"targetId\"] === \"string\" && value[\"targetId\"].length > 0"
                <> " && typeof value[\"url\"] === \"string\" && value[\"url\"].length > 0"
                <> " && isFrontendSurfaceFragmentProtection(value[\"protection\"])"

renderFrontendSurfaceMountConfig :: SurfaceIR -> [Text]
renderFrontendSurfaceMountConfig surface =
    [ "export type "
        <> name
        <> " = { surface: "
        <> quote surface.surfaceName
        <> "; scopeKey: string; mountKey: string; fragments: ReadonlyArray<"
        <> frontendSurfaceMountedFragmentConfigName surface
        <> ">; subscription: "
        <> subscriptionType
        <> " };"
    ]
        <> renderGuard name guardExpression
    where
        name = frontendSurfaceMountConfigName surface
        liveFragmentNames = surfaceLiveFragmentNames surface
        subscriptionType
            | null liveFragmentNames = "null"
            | otherwise = "{ scope: Extract<SurfaceScope, { surface: " <> quote surface.surfaceName <> " }> } | null"
        liveFragmentTest =
            "value[\"fragments\"].some((fragment) => isFrontendSurfaceLiveFragmentName("
                <> quote surface.surfaceName
                <> ", fragment.fragmentKey.kind))"
        validSubscription =
            "isRecord(value[\"subscription\"])"
                <> " && hasExactKeys(value[\"subscription\"], [\"scope\"])"
                <> " && isSurfaceScope(value[\"subscription\"].scope)"
                <> " && value[\"subscription\"].scope.surface === "
                <> quote surface.surfaceName
        subscriptionGuard
            | null liveFragmentNames = "value[\"subscription\"] === null"
            | otherwise =
                "((value[\"subscription\"] === null && !("
                    <> liveFragmentTest
                    <> ")) || (("
                    <> validSubscription
                    <> ") && ("
                    <> liveFragmentTest
                    <> ")))"
        guardExpression =
            "isRecord(value)"
                <> " && hasExactKeys(value, [\"surface\", \"scopeKey\", \"mountKey\", \"fragments\", \"subscription\"])"
                <> " && value[\"surface\"] === "
                <> quote surface.surfaceName
                <> " && typeof value[\"scopeKey\"] === \"string\" && value[\"scopeKey\"].length > 0"
                <> " && typeof value[\"mountKey\"] === \"string\" && value[\"mountKey\"].length > 0"
                <> " && Array.isArray(value[\"fragments\"]) && value[\"fragments\"].every((fragment) => is"
                <> frontendSurfaceMountedFragmentConfigName surface
                <> "(fragment))"
                <> " && ("
                <> subscriptionGuard
                <> ")"

frontendSurfaceMountedFragmentConfigName :: SurfaceIR -> Text
frontendSurfaceMountedFragmentConfigName surface = surfaceTypePrefix surface <> "MountedFragmentConfig"

frontendSurfaceMountConfigName :: SurfaceIR -> Text
frontendSurfaceMountConfigName surface = surfaceTypePrefix surface <> "MountConfig"

renderScope :: SurfaceIR -> ScopeIR -> [Text]
renderScope surface scope =
    renderRecordGuarded (surfaceTypePrefix surface <> typeNameFromMarker scope.scopeMarker <> "Scope") scope.scopeFields

renderFragment :: SurfaceIR -> FragmentIR -> [Text]
renderFragment surface fragment =
    renderRecordGuarded (surfaceTypePrefix surface <> typeNameFromMarker fragment.fragmentMarker <> "FragmentParams") fragment.fragmentParams

renderSchemaFor :: BrowserReachabilityIR -> SchemaIR -> [Text]
renderSchemaFor reachability schema =
    schemaTypeDeclaration schema <> renderReachableCodec reachability (schemaName schema) (schemaGuardExpression schema)

schemaName :: SchemaIR -> Text
schemaName = \case
    RecordIR _ name _ -> name
    EnumIR _ name _ -> name
    LiteralEnumIR _ name _ -> name
    TaggedUnionIR _ name _ _ -> name

schemaTypeDeclaration :: SchemaIR -> [Text]
schemaTypeDeclaration = \case
    RecordIR _ name fields -> ["export type " <> name <> " = " <> recordType fields <> ";"]
    EnumIR _ name values ->
        ["export type " <> name <> " ="] <> renderUnionValues values
    LiteralEnumIR _ name values ->
        ["export type " <> name <> " ="] <> renderUnionValues (fmap snd values)
    TaggedUnionIR _ name discriminator cases ->
        ["export type " <> name <> " ="] <> renderUnionCases discriminator cases

schemaGuardExpression :: SchemaIR -> Text
schemaGuardExpression = \case
    RecordIR _ _ fields -> recordGuardExpression fields
    EnumIR _ _ values -> isEnumExpression values
    LiteralEnumIR _ _ values -> isEnumExpression (fmap snd values)
    TaggedUnionIR _ _ discriminator cases -> "(" <> Text.intercalate " || " (fmap (caseGuard discriminator) cases) <> ")"

renderEventDetail :: BrowserReachabilityIR -> Text -> [FieldIR] -> [Text]
renderEventDetail BrowserUnreachableIR _ _ = []
renderEventDetail BrowserTypeOnlyIR _ _ = []
renderEventDetail reachability name fields =
    ["export type " <> name <> " = " <> recordType fields <> ";"]
        <> renderReachableCodec reachability name (recordGuardExpression fields)

renderRecordGuarded :: Text -> [FieldIR] -> [Text]
renderRecordGuarded name fields =
    ["export type " <> name <> " = " <> recordType fields <> ";"]
        <> renderGuard name (recordGuardExpression fields)

renderReachableCodec :: BrowserReachabilityIR -> Text -> Text -> [Text]
renderReachableCodec reachability name guardExpression =
    case reachability of
        BrowserUnreachableIR -> []
        BrowserTypeOnlyIR -> []
        BrowserGuardIR -> renderGuard name guardExpression
        BrowserInboundIR -> renderInboundCodec name guardExpression
        BrowserOutboundIR -> renderEncoder name
        BrowserBidirectionalIR -> renderInboundCodec name guardExpression <> renderEncoder name

renderGuard :: Text -> Text -> [Text]
renderGuard name guardExpression =
    [ "export function is" <> name <> "(value: unknown): value is " <> name <> " {"
    , "    return " <> guardExpression <> ";"
    , "}"
    , ""
    ]

renderInboundCodec :: Text -> Text -> [Text]
renderInboundCodec name guardExpression =
    renderGuard name guardExpression
        <> [ "export function parse" <> name <> "(value: unknown): " <> name <> " {"
           , "    if (is" <> name <> "(value)) return value;"
           , "    throw new Error(\"Invalid " <> name <> "\");"
           , "}"
           , ""
           ]

renderEncoder :: Text -> [Text]
renderEncoder name =
    [ "export function encode" <> name <> "(value: " <> name <> "): " <> name <> " { return value; }"
    , ""
    ]

renderUnionValues :: [Text] -> [Text]
renderUnionValues values =
    case values of
        [] -> ["    never;", ""]
        _  -> zipWith render values [0 :: Int ..]
    where
        render value index = (if index == 0 then "    " else "  | ") <> quote value <> if index == length values - 1 then ";" else ""

renderUnionCases :: Text -> [UnionCaseIR] -> [Text]
renderUnionCases discriminator cases =
    case cases of
        [] -> ["    never;", ""]
        _  -> zipWith render cases [0 :: Int ..]
    where
        render caseIR index =
            (if index == 0 then "    " else "  | ") <> (recordType (FieldIR "Discriminator" discriminator (WireRefIR (quote caseIR.unionCaseTag)) RequiredField : caseIR.unionCaseFields)) <> if index == length cases - 1 then ";" else ""

recordType :: [FieldIR] -> Text
recordType fields = "{ " <> Text.intercalate "; " (fmap renderField fields) <> " }"

renderField :: FieldIR -> Text
renderField field =
    propertyName field.fieldName <> optionalMarker field.fieldPresence <> ": " <> wireType field.fieldWire <> nullableSuffix field.fieldPresence

wireType :: WireIR -> Text
wireType = \case
    WireTextIR -> "string"
    WireIntIR -> "number"
    WireBoolIR -> "boolean"
    WireUuidIR -> wirePrimitiveTypeName WireUuidIR
    WireDayIR -> wirePrimitiveTypeName WireDayIR
    WireUnknownIR -> "unknown"
    WireListIR inner -> "ReadonlyArray<" <> wireType inner <> ">"
    WireMapIR key value -> "Record<" <> wireType key <> ", " <> wireType value <> ">"
    WireOptionalIR inner -> wireType inner <> " | undefined"
    WireNullableIR inner -> wireType inner <> " | null"
    WireRefIR name | Text.isPrefixOf "\"" name -> name
    WireRefIR name -> name
    WireSurfaceScopeIR -> "SurfaceScope"
    WireSurfaceFragmentKeyIR -> "SurfaceFragmentKey"

optionalMarker :: FieldPresence -> Text
optionalMarker = \case
    OptionalFieldPresence -> "?"
    RequiredField -> ""
    NullableFieldPresence -> ""

nullableSuffix :: FieldPresence -> Text
nullableSuffix = \case
    NullableFieldPresence -> " | null"
    RequiredField -> ""
    OptionalFieldPresence -> ""

recordGuardExpression :: [FieldIR] -> Text
recordGuardExpression fields =
    "isRecord(value) && hasExactKeys(value, ["
        <> Text.intercalate ", " (fmap (quote . (.fieldName)) fields)
        <> "], ["
        <> Text.intercalate ", " (fmap (quote . (.fieldName)) (filter ((/= OptionalFieldPresence) . (.fieldPresence)) fields))
        <> "])"
        <> mconcat (fmap fieldGuard fields)
    where
        fieldGuard field =
            let access = "value[" <> quote field.fieldName <> "]"
             in case field.fieldPresence of
                    RequiredField -> " && (" <> valueGuard access field.fieldWire <> ")"
                    OptionalFieldPresence -> " && (!(" <> quote field.fieldName <> " in value) || (" <> valueGuard access field.fieldWire <> "))"
                    NullableFieldPresence -> " && (" <> access <> " === null || (" <> valueGuard access field.fieldWire <> "))"

valueGuard :: Text -> WireIR -> Text
valueGuard access = \case
    WireTextIR -> "typeof " <> access <> " === \"string\""
    WireIntIR -> "typeof " <> access <> " === \"number\" && Number.isInteger(" <> access <> ")"
    WireBoolIR -> "typeof " <> access <> " === \"boolean\""
    WireUuidIR -> primitiveValueGuard access WireUuidIR
    WireDayIR -> primitiveValueGuard access WireDayIR
    WireUnknownIR -> "true"
    WireListIR inner -> "Array.isArray(" <> access <> ") && " <> access <> ".every((item) => " <> valueGuard "item" inner <> ")"
    WireMapIR key value -> "isRecord(" <> access <> ") && Object.entries(" <> access <> ").every(([key, entry]) => " <> valueGuard "key" key <> " && " <> valueGuard "entry" value <> ")"
    WireOptionalIR inner -> access <> " === undefined || " <> valueGuard access inner
    WireNullableIR inner -> access <> " === null || " <> valueGuard access inner
    WireRefIR name | Text.isPrefixOf "\"" name -> access <> " === " <> name
    WireRefIR name -> "is" <> name <> "(" <> access <> ")"
    WireSurfaceScopeIR -> "isSurfaceScope(" <> access <> ")"
    WireSurfaceFragmentKeyIR -> "isSurfaceFragmentKey(" <> access <> ")"

primitiveValueGuard :: Text -> WireIR -> Text
primitiveValueGuard access wire = "typeof " <> access <> " === " <> quote (wirePrimitiveRuntimeType wire)

isEnumExpression :: [Text] -> Text
isEnumExpression values = "typeof value === \"string\" && [" <> Text.intercalate ", " (fmap quote values) <> "].includes(value)"

caseGuard :: Text -> UnionCaseIR -> Text
caseGuard discriminator caseIR =
    "("
        <> recordGuardExpression
            (FieldIR "Discriminator" discriminator (WireRefIR (quote caseIR.unionCaseTag)) RequiredField : caseIR.unionCaseFields)
        <> ")"

surfaceTypePrefix :: SurfaceIR -> Text
surfaceTypePrefix surface = typeNameFromMarker surface.surfaceMarker

typeNameFromMarker :: Text -> Text
typeNameFromMarker marker
    | "-" `Text.isInfixOf` marker =
        marker
            |> Text.splitOn "-"
            |> filter (not . Text.null)
            |> fmap title
            |> mconcat
    | otherwise = Text.filter (/= '-') marker
    where
        title text =
            case Text.uncons text of
                Nothing -> ""
                Just (firstChar, rest) -> Text.singleton (Char.toUpper firstChar) <> rest

constName :: Text -> Text
constName marker =
    case Text.uncons (typeNameFromMarker marker) of
        Nothing -> "contract"
        Just (firstChar, rest) -> Text.singleton (Char.toLower firstChar) <> rest

propertyName :: Text -> Text
propertyName name
    | Text.all isIdentifierChar name && maybe False isIdentifierStart (fst <$> Text.uncons name) = name
    | otherwise = quote name
    where
        isIdentifierStart char = Char.isAlpha char || char == '_'
        isIdentifierChar char = Char.isAlphaNum char || char == '_'

quote :: Text -> Text
quote value = "\"" <> Text.replace "\\" "\\\\" (Text.replace "\"" "\\\"" value) <> "\""
