module Application.Helper.Frontend.Contracts
( OverlayLane(..)
, TypeScriptDeclaration(..)
, frontendContractDeclarations
, frontendContractsTypeScript
)
where

import IHP.Prelude
import qualified Data.Text as Text

data OverlayLane
    = DialogLane
    | PickerLane
    | ToastLane
    deriving (Eq, Show)

overlayLaneTypeName :: Text
overlayLaneTypeName = "OverlayLane"

overlayLaneValues :: [(OverlayLane, Text)]
overlayLaneValues =
    [ (DialogLane, "dialog")
    , (PickerLane, "picker")
    , (ToastLane, "toast")
    ]

data TypeScriptDeclaration = TypeScriptDeclaration
    { name :: Text
    , source :: Text
    } deriving (Eq, Show)

stringUnionDeclaration :: Text -> [Text] -> TypeScriptDeclaration
stringUnionDeclaration name values = TypeScriptDeclaration
    { name
    , source = Text.unlines $
        [ "export type " <> name <> " =" ]
        <> unionLines
    }
    where
        quotedValues = fmap (\value -> "\"" <> value <> "\"") values
        unionLines = case reverse quotedValues of
            [] -> [ "    never;" ]
            lastValue : reversedPrefix ->
                fmap ("    | " <>) (reverse reversedPrefix)
                <> [ "    | " <> lastValue <> ";" ]

frontendContractDeclarations :: [TypeScriptDeclaration]
frontendContractDeclarations =
    [ stringUnionDeclaration overlayLaneTypeName (fmap snd overlayLaneValues)
    ]

frontendContractsTypeScript :: Text
frontendContractsTypeScript = Text.unlines $
    [ "// @generated by Application.Helper.Frontend.Contracts"
    , "// Do not edit by hand. Run: bash ./bin/in-env frontend-contracts"
    , ""
    ]
    <> fmap source frontendContractDeclarations
