module Application.Helper.Frontend.TypeScript
    ( TypeScriptDeclaration (..)
    , TypeScriptDeclarationOrigin (..)
    , aesonTypeScriptDeclaration
    , legacyManualDeclaration
    , renderTypeScriptDeclarations
    , smallCompositionDeclaration
    , stringUnionDeclaration
    ) where

import Data.Aeson.TypeScript.TH (ExportMode (ExportEach),
                                 FormattingOptions (..),
                                 SumTypeFormat (TypeAlias), TSDeclaration,
                                 defaultFormattingOptions,
                                 formatTSDeclarations')
import qualified Data.Text as Text
import IHP.Prelude

-- | Where a generated frontend contract block came from.
--
-- The long-term direction is HaskellSchemaGenerated for every Haskell/TS shared
-- DTO. LegacyManual is a temporary marker for the pre-existing handwritten
-- live-update and interaction blocks while later tickets migrate them onto
-- Haskell-owned schemas.
data TypeScriptDeclarationOrigin
    = HaskellSchemaGenerated
    | SmallComposition
    | LegacyManual
    deriving (Eq, Show)

data TypeScriptDeclaration = TypeScriptDeclaration
    { name   :: !Text
    , origin :: !TypeScriptDeclarationOrigin
    , source :: !Text
    } deriving (Eq, Show)

aesonTypeScriptDeclaration :: Text -> [Text] -> [TSDeclaration] -> TypeScriptDeclaration
aesonTypeScriptDeclaration name headerLines declarations =
    TypeScriptDeclaration
        { name
        , origin = HaskellSchemaGenerated
        , source = Text.unlines headerLines <> formattedDeclarations
        }
    where
        formattedDeclarations =
            Text.pack $
                formatTSDeclarations'
                    defaultFormattingOptions
                        { numIndentSpaces = 4
                        , exportMode = ExportEach
                        , typeAlternativesFormat = TypeAlias
                        }
                    declarations

smallCompositionDeclaration :: Text -> Text -> TypeScriptDeclaration
smallCompositionDeclaration name source =
    TypeScriptDeclaration
        { name
        , origin = SmallComposition
        , source
        }

legacyManualDeclaration :: Text -> Text -> TypeScriptDeclaration
legacyManualDeclaration name source =
    TypeScriptDeclaration
        { name
        , origin = LegacyManual
        , source
        }

stringUnionDeclaration :: Text -> [Text] -> TypeScriptDeclaration
stringUnionDeclaration name values =
    smallCompositionDeclaration name $
        Text.unlines $
            [ "export type " <> name <> " =" ]
                <> unionLines
    where
        quotedValues = fmap (\value -> "\"" <> value <> "\"") values
        unionLines = case reverse quotedValues of
            [] -> [ "    never;" ]
            lastValue : reversedPrefix ->
                fmap ("    | " <>) (reverse reversedPrefix)
                    <> [ "    | " <> lastValue <> ";" ]

renderTypeScriptDeclarations :: [TypeScriptDeclaration] -> Text
renderTypeScriptDeclarations declarations =
    Text.unlines $
        [ "// @generated by Application.Helper.Frontend.Contracts"
        , "// Do not edit by hand. Run: bash ./bin/in-env frontend-contracts"
        , ""
        ]
            <> fmap source declarations
