module Application.Helper.Frontend.TypeScript
    ( TypeScriptDeclaration (..)
    , TypeScriptDeclarationOrigin (..)
    , renderTypeScriptDeclarations
    ) where

import qualified Data.Text as Text
import IHP.Prelude

-- | Where a frontend contract block came from. Browser-boundary DTOs shared
-- between Haskell and TypeScript should use HaskellSchemaGenerated.
data TypeScriptDeclarationOrigin
    = HaskellSchemaGenerated
    deriving (Eq, Show)

data TypeScriptDeclaration = TypeScriptDeclaration
    { name   :: !Text
    , origin :: !TypeScriptDeclarationOrigin
    , source :: !Text
    } deriving (Eq, Show)

renderTypeScriptDeclarations :: [TypeScriptDeclaration] -> Text
renderTypeScriptDeclarations declarations =
    Text.unlines $
        [ "// @generated by Application.Helper.Frontend.Contracts"
        , "// Do not edit by hand. Run: bash ./bin/in-env frontend-contracts"
        , ""
        ]
            <> fmap source declarations
