import "./frontend-surface-contracts.test";
import "./linked-highlight.test";
import "./complete-set-sort.test";
import "./surface-tab-set.test";
import "./interaction-contracts.test";
import "./interaction-runtime.test";
import "./shared.test";
import "./toggle.test";
import "./time-picker.test";
import "./ordered-range.test";
import "./horizontal-scroll.test";
import "./pwa-install.test";
import "./xero-candidate-filter.test";
import "./low-risk.test";
import "./medium-risk.test";
import "./overlay.test";
import "./live-updates.test";
import "./live-updates-validation.test";
import "./lazy-surface.test";
import "./ui-region-events.test";
import "./ui-region-transitions.test";
import "./roster.test";
import { runTests } from "./harness";

await runTests();
