import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { chmodSync, copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

const repo = fileURLToPath(new URL('../', import.meta.url));
const scripts = join(repo, 'Config/nix/scripts');
const artifacts = execFileSync(join(repo, 'bin/tooling-run'), ['artifacts', '--print-binary'], { encoding: 'utf8' }).trim();
const managed = 'Application/Helper/FrontendContract/Surface/Fixture/Generated/Action.hs';
const generated = `-- @generated by Application.Helper.FrontendContract.Surface.HaskellAdapter.Generator
module Application.Helper.FrontendContract.Surface.Fixture.Generated.Action where

import Application.Dependency (dependency)

value :: Int
value = dependency
`;
const proof = `module Proof where
import Application.Helper.FrontendContract.Surface.Fixture.Generated.Action (value)
check :: Int
check = value
`;

function put(root, path, contents) {
    const file = join(root, path);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, contents);
}

function fixture(t) {
    const root = mkdtempSync(join(tmpdir(), 'bepis-adapter-check-'));
    t.after(() => rmSync(root, { recursive: true, force: true }));
    put(root, 'Makefile', 'print-ghc-options:\n\t@echo "-i. -O0"\n');
    put(root, 'App.cabal', 'cabal-version: 2.4\nname: adapter-check-fixture\nversion: 0.1.0.0\nbuild-type: Simple\nlibrary\n  default-language: Haskell2010\n  build-depends: base\n');
    put(root, 'flake.lock', '{}');
    for (const path of ['lib/ghc.sh', 'haskell/verification-cache-inputs']) {
        const file = join(root, 'Config/nix/scripts', path);
        mkdirSync(dirname(file), { recursive: true });
        copyFileSync(join(scripts, path), file);
    }
    put(root, 'Application/Dependency.hs', 'module Application.Dependency where\ndependency :: Int\ndependency = 1\n');
    put(root, 'inputs/Action.hs', generated);
    put(root, 'inputs/Proof.hs', proof);
    execFileSync('stylish-haskell', ['-i', join(root, 'inputs/Action.hs')], { cwd: root });
    put(root, managed, readFileSync(join(root, 'inputs/Action.hs')));
    // Only generation is synthetic. Formatting, comparison, cache ownership,
    // GHC and both fresh generated/proof subjects use the actual checker.
    put(root, 'tools/bin/generate-frontend-surface-adapters', `#!/usr/bin/env bash
set -euo pipefail
mkdir -p "$1/$(dirname '${managed}')"
cp inputs/Action.hs "$1/${managed}"
cp inputs/Proof.hs "$2/Proof.hs"
`);
    chmodSync(join(root, 'tools/bin/generate-frontend-surface-adapters'), 0o755);
    execFileSync('git', ['init', '-q'], { cwd: root });
    const identity = execFileSync(artifacts, ['digest', '--truncate', '12', root], { encoding: 'utf8' }).trim();
    const cache = join(root, 'cache', identity, 'surface-adapter-validation');
    const run = () => {
        const result = spawnSync('bash', [join(scripts, 'frontend/surface-adapters-check')], {
            cwd: root, encoding: 'utf8', timeout: 60_000,
            env: { ...process.env, FRONTEND_REPO_ROOT: root, BEPIS_SCRIPTS_ROOT: scripts,
                FRONTEND_CONTRACT_TOOLS_ROOT: join(root, 'tools'), IHP_ROSTER_ARTIFACTS_BINARY: artifacts,
                BEPIS_GHC_CACHE_PARENT: join(root, 'cache') },
        });
        assert.ifError(result.error);
        return result;
    };
    const passes = () => {
        const result = run();
        assert.equal(result.status, 0, result.stdout + result.stderr);
    };
    return { root, cache, run, passes };
}

test('fresh adapter stages reuse unchanged dependencies, but still compile each new proof and dependency edit', (t) => {
    const { root, cache, run, passes } = fixture(t);
    passes();
    const dependency = join(cache, 'obj/Application/Dependency.o');
    const original = statSync(dependency, { bigint: true }).mtimeNs;
    const fingerprint = readFileSync(join(cache, 'fingerprint.json'), 'utf8');
    passes();
    assert.equal(statSync(dependency, { bigint: true }).mtimeNs, original, 'temporary input paths must not discard dependency objects');
    assert.equal(readFileSync(join(cache, 'fingerprint.json'), 'utf8'), fingerprint);

    put(root, 'inputs/Proof.hs', proof.replace('check :: Int', 'check :: Bool'));
    let result = run();
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /Couldn't match expected type/);
    put(root, 'inputs/Proof.hs', proof);
    passes();

    put(root, 'Application/Dependency.hs', 'module Application.Dependency where\ndependency :: Bool\ndependency = True\n');
    result = run();
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /Couldn't match expected type/);
});

test('typecorrect but stale generated output still fails exact comparison', (t) => {
    const { root, run, passes } = fixture(t);
    passes();
    put(root, 'inputs/Action.hs', generated.replace('value = dependency', 'value = dependency + 1'));
    const result = run();
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /is stale/);
});
