cabal-version: 3.0
name: bepis-postgres
version: 0.1.0.0
build-type: Simple
license: Apache-2.0

library
  exposed-modules:
      Bepis.Tooling.Postgres
      Bepis.Tooling.Postgres.Config
  other-modules:
      Bepis.Tooling.Postgres.Lifecycle
  hs-source-dirs: src
  build-depends:
      base >=4.18 && <5
    , bepis-tooling-core
    , bepis-workspace-state
    , bytestring
    , directory
    , filepath
    , process
    , text
    , time
    , unix
  default-language: GHC2021
  ghc-options: -Wall -Wcompat -Werror

executable bepis-postgres
  main-is: Main.hs
  hs-source-dirs: app
  build-depends:
      base
    , bepis-postgres
  default-language: GHC2021
  ghc-options: -Wall -Wcompat -Werror

test-suite bepis-postgres-test
  type: exitcode-stdio-1.0
  main-is: Main.hs
  hs-source-dirs: test
  build-depends:
      base
    , bepis-postgres
    , directory
    , filepath
    , temporary
  default-language: GHC2021
  ghc-options: -Wall -Wcompat -Werror
