name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    name: Typecheck and Hspec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
          extra-conf: "lazy-trees = true"

      - name: Cachix
        uses: cachix/cachix-action@v15
        with:
          name: digitallyinduced
          skipPush: true

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /opt/hostedtoolcache
          sudo docker system prune -af

      - name: Typecheck
        run: bash ./bin/in-env typecheck

      - name: Hspec
        run: bash ./bin/in-env hspec-test
