module Web.Routes where
import Generated.Types
import IHP.RouterPrelude
import Web.Types

-- Generator Marker
instance AutoRoute StaticController
instance AutoRoute SessionsController
instance AutoRoute AuthController
instance AutoRoute PasskeysController
instance AutoRoute UsersController
instance AutoRoute ProfilesController
instance AutoRoute TimesheetsController
instance AutoRoute LeaveRequestsController
instance AutoRoute ExportsController
instance AutoRoute StaffDocumentsController
instance AutoRoute AdminController
instance AutoRoute SupportController
instance AutoRoute StaffController
instance AutoRoute RosterWeeksController
